let state={servers:[],experiments:[],events:[],transactions:[],workloads:[],accountSnapshots:[]}, metrics={},buildProfile={},overviewExperimentId='',transactionExperimentId='';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const htmlCache=new Map(),optionCache=new WeakMap();
async function api(path,options={}){const r=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});if(!r.ok){const payload=await r.json(),error=new Error(payload.error||r.statusText);error.payload=payload;throw error}return r.status===204?null:r.json()}
function toast(s){const x=$('#toast');x.textContent=s;x.style.display='block';setTimeout(()=>x.style.display='none',3000)}
function status(s){return `<span class="status ${s==='failed'||s==='error'||s==='timeout'||String(s).includes('errors')?'failed':''}">${esc(s)}</span>`}
function short(s,n=18){s=String(s||'');return s.length>n?s.slice(0,n)+'…':s}
function age(s){return s?new Date(s).toLocaleString():'尚未查询'}
function hexDecimal(s){if(!s)return '—';try{return `${esc(s)} <small>(${BigInt(s).toString(10)})</small>`}catch{return esc(s)}}
function fmtUs(us){us=Number(us||0);if(us<=0)return '—';if(us<1000)return `${us} µs`;if(us<1000000)return `${(us/1000).toFixed(us<10000?2:1)} ms`;return `${(us/1000000).toFixed(2)} s`}
function txUs(t,name){return Number(t[name+'DurationUs']||0)||Number(t[name+'DurationMs']||0)*1000}
function transferTimings(t){if(t.type!=='transfer')return '';return `<details class="participant-timings"><summary>查看 Transfer 双方分阶段耗时</summary><div class="participant-grid"><section><b>付款节点</b><span>证明生成 ${fmtUs(t.payerProofGenerationUs)}</span><span>证明验证 ${fmtUs(t.payerProofVerificationUs)}</span><span>交易/状态包生成 ${fmtUs(t.payerTxGenerationUs)}</span><span>交易验证 ${fmtUs(t.payerTxVerificationUs)}</span></section><section><b>收款节点</b><span>证明生成 ${fmtUs(t.receiverProofGenerationUs)}</span><span>证明验证 ${fmtUs(t.receiverProofVerificationUs)}</span><span>交易生成 ${fmtUs(t.receiverTxGenerationUs)}</span><span>交易验证 ${fmtUs(t.receiverTxVerificationUs)}</span></section></div></details>`}
function diffUs(a,b){return a&&b?Math.max(0,(new Date(b)-new Date(a))*1000):0}
function systemInfo(s){return Object.fromEntries(String(s||'').split('\n').filter(Boolean).map(line=>{const i=line.indexOf('=');return i<0?[line,'']:[line.slice(0,i),line.slice(i+1)]}))}
function pct(used,total){return total>0?`${Math.max(0,Math.min(100,used/total*100)).toFixed(1)}%`:'—'}
function newestFirst(items,dateField='createdAt'){return items.slice().sort((a,b)=>new Date(b[dateField]||b.createdAt||0)-new Date(a[dateField]||a.createdAt||0))}
function patchHTML(selector,html){if(htmlCache.get(selector)===html)return false;htmlCache.set(selector,html);$(selector).innerHTML=html;return true}
function setOptions(select,html){if(optionCache.get(select)===html)return false;const selected=[...select.selectedOptions].map(x=>x.value);select.innerHTML=html;for(const option of select.options)option.selected=selected.includes(option.value);optionCache.set(select,html);return true}
function experimentActions(e){const active=['running','deploying','stopping'].includes(e.status),canDeploy=['draft','stopped','failed'].includes(e.status);return `<div class="row-actions">${canDeploy?`<button class="action" onclick="experiment('${e.id}','deploy')">部署/启动</button>`:''}${e.status==='running'?`<button class="action secondary" onclick="experiment('${e.id}','stop')">停止</button>`:''}<a class="action secondary" href="/api/experiments/${e.id}/report">导出报告</a>${active?'':`<button class="action danger" onclick="deleteExperiment('${e.id}')">删除</button>`}</div>`}
function experimentDetail(e){return `<div class="row experiment-detail" data-experiment="${e.id}"><div class="row-title"><b>${esc(e.name)}</b>${status(e.status)}</div><div class="meta"><span>${e.nodes?.length||0} 个节点</span><span>${esc(e.topology)}</span><span>Network ID ${e.networkId}</span><span>${new Date(e.createdAt).toLocaleString()}</span></div><div class="node-list">${(e.nodes||[]).map(n=>`<div class="node-line"><span>${esc(n.name)} · ${status(n.status)}</span><span>区块 ${n.block||0}</span><span>${n.peers||0} peers</span><code title="${esc(n.account||'')}">${esc(short(n.account||'无账户',22))}</code></div>`).join('')||'<span class="empty compact">尚未部署节点</span>'}</div>${e.error?`<p class="status failed breakable">${esc(e.error)}</p>`:''}${experimentActions(e)}</div>`}
function experimentSummary(e){const nodes=e.nodes||[],running=nodes.filter(n=>n.status==='running').length,maxBlock=nodes.reduce((n,x)=>Math.max(n,Number(x.block||0)),0),peers=nodes.reduce((n,x)=>n+Number(x.peers||0),0);return `<div class="overview-experiment"><div class="row-title"><b>${esc(e.name)}</b>${status(e.status)}</div><div class="experiment-stats"><div><b>${running}/${nodes.length}</b><span>节点在线</span></div><div><b>${maxBlock}</b><span>最高区块</span></div><div><b>${peers}</b><span>Peer 总数</span></div></div><div class="meta"><span>${esc(e.topology)}</span><span>${new Date(e.createdAt).toLocaleString()}</span></div>${e.error?`<p class="status failed breakable">${esc(short(e.error,100))}</p>`:''}<button class="action secondary" onclick="showExperiment('${e.id}')">管理实验</button></div>`}
function render(){
 const active=document.querySelector('.tab.active')?.id||'overview';
	const recentExperiments=newestFirst(state.experiments);
 $('#serverCount').textContent=state.servers.length;$('#nodeCount').textContent=state.experiments.reduce((n,e)=>n+(e.nodes?.length||0),0);$('#txCount').textContent=state.transactions.length;
 if(active==='servers')patchHTML('#serverRows',state.servers.map(s=>{const x=systemInfo(s.systemInfo),cpus=Number(x.cpus||0),memory=Number(x.memory_kb||0),available=Number(x.memory_available_kb||0),disk=Number(x.disk_total_kb||0),diskAvailable=Number(x.disk_available_kb||0),load=Number(x.load1||0);return `<div class="row server-row"><div class="row-title"><b>${esc(s.name)}</b>${status(s.status)}</div><div class="meta"><span>${esc(s.user)}@${esc(s.host)}:${s.port}</span><span>${esc(s.workDir)}</span></div><div class="server-load"><span><b>${load||'—'}</b>1 分钟负载${cpus?` / ${cpus} CPU`:''}</span><span><b>${pct(memory-available,memory)}</b>内存使用</span><span><b>${pct(disk-diskAvailable,disk)}</b>磁盘使用</span></div><div class="meta"><span>${esc(x.host||'')}</span><span>${esc(x.kernel||'')}</span><span>更新 ${age(s.lastCheck)}</span></div><div class="row-actions"><button class="action" onclick="checkServer('${s.id}')">立即刷新</button>${s.host==='local'||s.host==='localhost-local'?'':`<button class="action secondary" onclick="trustServer('${s.id}')">信任 SSH 主机密钥</button>`}</div></div>`}).join('')||'<div class="empty">尚未配置 SSH 服务器</div>');
 if(active==='experiments')setOptions($('#serverSelect'),state.servers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join(''));
	if(active==='experiments'){const keys=Object.entries(buildProfile.keys||{});patchHTML('#buildProfile',buildProfile.recordedAt?`<div class="build-summary"><span><b>${fmtUs(Number(buildProfile.libsnarkBuildDurationMs||0)*1000)}</b>电路编译</span><span><b>${fmtUs(Number(buildProfile.keyGenerationDurationMs||0)*1000)}</b>全部密钥生成</span><span><b>${buildProfile.cpus||'—'}</b>CPU 核心</span><span><b>${buildProfile.memoryKb?`${(buildProfile.memoryKb/1048576).toFixed(1)} GiB`:'—'}</b>主机内存</span></div><div class="meta"><span>${esc(buildProfile.host)}</span><span>${esc(buildProfile.kernel)}</span><span>${esc(buildProfile.cpuModel)}</span><span>${esc(buildProfile.compiler)}</span><span>${esc(buildProfile.recordedAt)}</span></div><div class="key-sizes">${keys.map(([name,v])=>`<span><b>${esc(name)}</b>${(Number(v.bytes||0)/1048576).toFixed(2)} MiB</span>`).join('')}</div>`:'<div class="empty compact">下次执行 ./build.sh keys 或 ./build.sh all 后生成构建档案。</div>')}
	const visibleExperiments=overviewExperimentId?recentExperiments.filter(e=>e.id===overviewExperimentId):recentExperiments,exps=recentExperiments.map(experimentDetail).join('');
 if(active==='experiments')patchHTML('#experimentRows',exps||'<div class="empty">尚无实验</div>');
	if(active==='overview'){setOptions($('#overviewExperiment'),`<option value="">全部实验</option>${recentExperiments.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}`);$('#overviewExperiment').value=overviewExperimentId;const scope=state.experiments.find(e=>e.id===overviewExperimentId);$('#overviewScopeHint').textContent=scope?`${scope.name} 的独立统计`:'全部实验的聚合统计';patchHTML('#experimentCards',visibleExperiments.map(experimentSummary).join('')||'尚无实验')}
	if(active==='transactions'){const running=newestFirst(state.experiments.filter(e=>e.status==='running'),'startedAt'),allOptions=recentExperiments.map(e=>`<option value="${e.id}">${esc(e.name)} · ${esc(e.status)}</option>`).join(''),runningOptions=running.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');if(!state.experiments.some(e=>e.id===transactionExperimentId))transactionExperimentId=running[0]?.id||recentExperiments[0]?.id||'';setOptions($('#experimentSelect'),allOptions);$('#experimentSelect').value=transactionExperimentId;updateNodes();setOptions($('#consoleExperiment'),runningOptions);if(running.some(e=>e.id===transactionExperimentId))$('#consoleExperiment').value=transactionExperimentId;updateConsoleNodes();renderAccounts();renderTransactions();renderWorkloads()}
 if(active==='overview'){patchHTML('#metrics',[['确认交易',metrics.confirmed||0],['成功率',`${((metrics.successRate||0)*100).toFixed(1)}%`],['历史平均 TPS',(metrics.confirmedTPS||0).toFixed(4)],['端到端 p95',`${metrics.latencyP95Ms||0} ms`],['证明 p95',fmtUs(metrics.proofP95Us)],['验证 p95',fmtUs(metrics.verifyP95Us)]].map(x=>`<div class="metric"><b>${x[1]}</b><span>${x[0]}</span></div>`).join(''));const events=state.events.filter(e=>!overviewExperimentId||e.experimentId===overviewExperimentId);patchHTML('#events',events.slice(-100).reverse().map(e=>`<div class="event ${e.level}"><time>${new Date(e.at).toLocaleTimeString()}</time>${esc(e.message)}</div>`).join('')||'<div class="empty">该范围内尚无事件</div>')}
}
function renderTransactions(){const experimentId=$('#experimentSelect').value,e=state.experiments.find(x=>x.id===experimentId);$('#transactionScope').textContent=e?`${e.name} · 仅显示本实验记录`:'请选择实验';const open=new Set([...document.querySelectorAll('#transactionRows .tx details[open]')].map(x=>x.closest('.tx')?.dataset.tx));const html=state.transactions.filter(t=>t.experimentId===experimentId).slice().reverse().map(t=>{const endToEnd=diffUs(t.submittedAt,t.confirmedAt),queue=diffUs(t.submittedAt,t.provingAt),chain=diffUs(t.broadcastAt,t.confirmedAt);let receipt='';try{receipt=JSON.stringify(JSON.parse(t.receipt),null,2)}catch{receipt=t.receipt}return `<div class="row tx" data-tx="${t.id}"><div><b>${esc(t.type)}</b> ${status(t.status)} ${t.workloadId?`<span class="workload-tag">自动 #${t.sequence}</span>`:''}</div><div class="meta"><span>${esc(t.fromNode)}${t.toNode?' → '+esc(t.toNode):' · 单节点状态交易'}</span><span>值 ${esc(t.value||'—')}</span><span>区块 ${esc(t.blockNumber||'—')}</span></div><div class="timings"><span>排队 ${fmtUs(queue)}</span><span>证明生成 ${fmtUs(txUs(t,'proof'))}</span><span>证明验证 ${fmtUs(txUs(t,'verify'))}</span><span>交易生成 ${fmtUs(t.txGenerationUs)}</span><span>交易验证 ${fmtUs(t.txVerificationUs)}</span><span>链上确认 ${fmtUs(chain)}</span></div>${transferTimings(t)}${t.status==='confirmed'?`<div class="meta"><span>端到端总耗时 ${fmtUs(endToEnd)}</span></div>`:''}${t.command?`<details class="tx-command"><summary>查看实际执行指令</summary><pre>${esc(t.command)}</pre></details>`:''}${t.hash?`<code title="${esc(t.hash)}">${esc(t.hash)}</code>`:''}${t.receipt?`<details><summary>查看链上 Receipt${t.receiptStatus?' · status '+esc(t.receiptStatus):''}</summary><pre>${esc(receipt)}</pre></details>`:''}${t.error?`<p class="status failed">${esc(t.error)}</p>`:''}</div>`}).join('')||'<div class="empty">该实验尚无交易</div>';if(patchHTML('#transactionRows',html))for(const id of open){const d=document.querySelector(`#transactionRows [data-tx="${id}"] details`);if(d)d.open=true}}
function renderWorkloads(){const selected=$('#experimentSelect').value,rows=state.workloads.filter(w=>w.experimentId===selected).slice().reverse();patchHTML('#workloadRows',rows.map(w=>{const txs=state.transactions.filter(t=>t.workloadId===w.id).sort((a,b)=>a.sequence-b.sequence),confirmed=txs.filter(t=>t.status==='confirmed').length,failed=txs.filter(t=>t.status==='failed'||t.status==='timeout').length,inflight=txs.length-confirmed-failed;return `<div class="row workload"><div><b>${esc(w.name)}</b> ${status(w.status)}</div><div class="meta"><span>${esc(w.type)} · ${esc(w.strategy)}</span><span>已投递 ${w.submitted}</span><span>成功 ${confirmed}</span><span>失败 ${failed}</span><span>处理中 ${inflight}</span></div><details><summary>查看实际节点路由（${txs.length} 笔）</summary>${txs.map(t=>`<div class="route"><b>#${t.sequence}</b><span>${esc(t.fromNode)}${t.toNode?' → '+esc(t.toNode):' · 单节点状态交易'}</span>${status(t.status)}</div>`).join('')||'<div class="empty">尚未投递</div>'}</details>${w.error?`<p class="status failed">${esc(w.error)}</p>`:''}</div>`}).join('')||'<div class="empty compact">该实验尚无自动交易规则</div>')}
function renderAccounts(){const id=$('#experimentSelect').value,e=state.experiments.find(x=>x.id===id),nodes=e?.nodes||[],signature=JSON.stringify(nodes.map(n=>[n.id,n.name,n.status,n.account,n.publicBalance,n.zkBalance,n.commitment,n.lastTxBlock,n.stateError,n.peers]));if(htmlCache.get('#accountCards:signature')!==signature){htmlCache.set('#accountCards:signature',signature);patchHTML('#accountCards',nodes.map(n=>`<div class="account-card" data-node="${n.id}"><div class="account-title"><b>${esc(n.name)}</b>${status(n.status)}</div><code title="${esc(n.account)}">${esc(n.account||'无账户')}</code><dl><dt>公开余额（wei）</dt><dd>${esc(n.publicBalance||'—')}</dd><dt>隐私余额</dt><dd>${hexDecimal(n.zkBalance)}</dd><dt>承诺值</dt><dd title="${esc(n.commitment)}">${esc(short(n.commitment,30)||'—')}</dd><dt>隐私状态区块</dt><dd>${esc(n.lastTxBlock||'—')}</dd><dt>当前链高度</dt><dd data-block>${n.block||0}</dd><dt>最后查询</dt><dd data-seen>${age(n.lastSeen)}</dd></dl>${n.stateError?`<p class="warning">隐私状态：${esc(n.stateError)}</p>`:''}<button class="action" onclick="queryNode('${e.id}','${n.id}')">立即查询链上状态</button></div>`).join('')||'<div class="empty">请选择运行中的实验</div>')}for(const n of nodes){const card=document.querySelector(`#accountCards [data-node="${n.id}"]`);if(card){card.querySelector('[data-block]').textContent=n.block||0;card.querySelector('[data-seen]').textContent=age(n.lastSeen)}}const rows=(state.accountSnapshots||[]).filter(s=>s.experimentId===id).slice().reverse();patchHTML('#accountHistory',rows.map(s=>`<div class="history-row"><time>${age(s.at)}</time><b>${esc(s.nodeId)}</b><span>公开 ${esc(s.publicBalance||'—')}</span><span>隐私 ${hexDecimal(s.zkBalance)}</span><span>区块 ${s.chainBlock}</span><small>${esc(s.reason)}</small></div>`).join('')||'<div class="empty">首次查询或账户状态变化后会在这里留下记录</div>')}
function updateNodes(){const experimentId=$('#experimentSelect').value,e=state.experiments.find(x=>x.id===experimentId),options=(e?.nodes||[]).map(n=>`<option value="${n.id}">${esc(n.name)} · ${esc(n.status)}</option>`).join('');$('#transactionExperimentId').value=experimentId;$('#workloadExperiment').value=experimentId;setOptions($('#nodeSelect'),options);updateDestinationOptions();const disabled=e?.status!=='running';$('#startWorkload').disabled=disabled;$('#transactionContextHint').textContent=e?`${e.status} · ${e.nodes?.length||0} 个节点 · Network ID ${e.networkId}${disabled?' · 历史查看模式':''}`:'暂无实验';updateCommandPreview()}
function updateDestinationOptions(){const form=$('#transactionForm'),e=state.experiments.find(x=>x.id===form.elements.experimentId.value),from=form.elements.fromNode.value,type=form.elements.type.value,nodes=e?.nodes||[],needsTarget=type==='transfer'||type==='public',choices=type==='transfer'?nodes.filter(n=>n.id!==from):nodes;setOptions($('#toNodeSelect'),choices.map(n=>`<option value="${n.id}">${esc(n.name)} · ${esc(n.status)}</option>`).join(''));$('#toNodeSelect').disabled=!needsTarget;$('#toNodeSelect').closest('label').classList.toggle('field-disabled',!needsTarget);$('#queueTransaction').disabled=e?.status!=='running'||(type==='transfer'&&choices.length===0)}
function updateCommandPreview(){const form=$('#transactionForm'),e=state.experiments.find(x=>x.id===form.elements.experimentId.value),from=e?.nodes?.find(x=>x.id===form.elements.fromNode.value),to=e?.nodes?.find(x=>x.id===form.elements.toNode.value),type=form.elements.type.value,value=form.elements.value.value||'0x1',q=JSON.stringify(value);let command='';if(!from){$('#transactionCommand').textContent='请选择运行中的实验和节点';return}if(type==='createAccount')command=`${from.name}: eth.sendCreateAccountTransaction({from:eth.accounts[0]})`;if(type==='mint')command=`${from.name}: eth.sendMintTransaction({from:eth.accounts[0],value:${q}})`;if(type==='redeem')command=`${from.name}: eth.sendRedeemTransaction({from:eth.accounts[0],value:${q}})`;if(type==='public')command=to?`${from.name}: eth.sendPublicTransaction({from:eth.accounts[0],to:${JSON.stringify(to.account)},value:${q}})`:'请选择目标节点';if(type==='transfer')command=to?`${from.name}: JSON.stringify(eth.getPayerNextState('0x01',${q}))\n${to.name}: eth.sendTransferTransaction({from:eth.accounts[0],value:${q},rs:'0x01',cmtANew:<payer.cmtANew>,snAOld:<payer.snAOld>,proofA:<payer.proofA>})`:'请选择目标节点';$('#transactionCommand').textContent=command}
function updateConsoleNodes(){const e=state.experiments.find(x=>x.id===$('#consoleExperiment').value),options=(e?.nodes||[]).filter(n=>n.status==='running').map(n=>`<option value="${n.id}">${esc(n.name)} · ${esc(n.account||'无账户')}</option>`).join('');setOptions($('#consoleNode'),options)}
let refreshing=false,refreshQueued=false,refreshTimer;async function refresh(){if(refreshing){refreshQueued=true;return}refreshing=true;try{[state,metrics,buildProfile]=await Promise.all([api('/state'),api(`/metrics${overviewExperimentId?'?experimentId='+encodeURIComponent(overviewExperimentId):''}`),api('/build-profile')]);if(overviewExperimentId&&!state.experiments.some(e=>e.id===overviewExperimentId)){overviewExperimentId='';metrics=await api('/metrics')}render()}finally{refreshing=false;if(refreshQueued){refreshQueued=false;scheduleRefresh(100)}}}function scheduleRefresh(delay=250){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(e=>toast(e.message)),delay)}
async function checkServer(id){try{toast('正在检查 SSH…');await api(`/servers/${id}/check`,{method:'POST'});await refresh()}catch(e){toast(e.message);await refresh()}}
async function trustServer(id){const server=state.servers.find(s=>s.id===id);if(!confirm(`请先通过可信渠道核对 ${server?.host||id} 的 SSH 主机指纹。\n\n确认采用首次使用信任（TOFU）并保存当前主机密钥吗？`))return;try{await api(`/servers/${id}/trust-host-key`,{method:'POST'});toast('主机密钥已保存，正在重新检查连接');await checkServer(id)}catch(e){toast(e.message)}}
function showExperiment(id){document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));document.querySelector('nav button[data-tab="experiments"]').classList.add('active');$('#experiments').classList.add('active');render();requestAnimationFrame(()=>document.querySelector(`[data-experiment="${id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}))}
async function experiment(id,action){try{await api(`/experiments/${id}/${action}`,{method:'POST'});toast('任务已进入后台');await refresh()}catch(e){toast(e.message)}}
async function deleteExperiment(id){const name=state.experiments.find(e=>e.id===id)?.name||id;if(!confirm(`确定删除实验“${name}”吗？\n\n该实验的交易、自动负载、账户快照和事件记录也会永久删除。`))return;try{await api(`/experiments/${id}`,{method:'DELETE'});toast('实验及关联记录已删除');await refresh()}catch(e){toast(e.message)}}
async function queryNode(experimentId,nodeId){try{toast('正在查询节点链上状态…');await api(`/experiments/${experimentId}/nodes/${nodeId}/state`,{method:'POST'});await refresh();toast('账户状态已更新')}catch(e){toast(e.message)}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');render()});
$('#serverForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.port=+v.port;try{await api('/servers',{method:'POST',body:JSON.stringify(v)});e.target.reset();await refresh()}catch(x){toast(x.message)}};
$('#experimentForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target)), ids=[...$('#serverSelect').selectedOptions].map(x=>x.value);const body={name:v.name,artifactPath:v.artifactPath,networkId:+v.networkId,p2pPortBase:+v.p2pPortBase,rpcPortBase:+v.rpcPortBase,topology:'full-mesh',placements:ids.map(serverId=>({serverId,count:+v.count}))};try{await api('/experiments',{method:'POST',body:JSON.stringify(body)});await refresh()}catch(x){toast(x.message)}};
$('#transactionForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{await api('/transactions',{method:'POST',body:JSON.stringify(body)});toast('交易已排队');await refresh()}catch(x){toast(x.message)}};$('#experimentSelect').onchange=()=>{const id=$('#experimentSelect').value;transactionExperimentId=id;if(state.experiments.find(e=>e.id===id)?.status==='running')$('#consoleExperiment').value=id;updateNodes();updateConsoleNodes();renderAccounts();renderTransactions();renderWorkloads()};
$('#transactionForm').addEventListener('input',updateCommandPreview);$('#transactionForm').addEventListener('change',()=>{updateDestinationOptions();updateCommandPreview()});
$('#workloadForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.ratePerSecond=+body.ratePerSecond;body.durationSeconds=+body.durationSeconds;body.strategy='round-robin';try{await api('/workloads',{method:'POST',body:JSON.stringify(body)});toast('自动负载已启动');await refresh()}catch(x){toast(x.message)}};
$('#overviewExperiment').onchange=e=>{overviewExperimentId=e.target.value;refresh().catch(x=>toast(x.message))};
$('#openConsole').onclick=()=>{const selected=$('#experimentSelect').value;if(state.experiments.find(e=>e.id===selected)?.status==='running')$('#consoleExperiment').value=selected;updateConsoleNodes();$('#nodeConsole').showModal();setTimeout(()=>$('#consoleCommand').focus(),0)};
$('#closeConsole').onclick=()=>$('#nodeConsole').close();$('#nodeConsole').onclick=e=>{if(e.target===$('#nodeConsole'))$('#nodeConsole').close()};$('#consoleExperiment').onchange=updateConsoleNodes;
document.querySelectorAll('.console-examples button').forEach(b=>b.onclick=()=>{$('#consoleCommand').value=b.dataset.command;$('#consoleCommand').focus()});
$('#consolePreset').onchange=e=>{if(!e.target.value)return;$('#consoleCommand').value=e.target.value;$('#consoleCommand').focus();e.target.selectedIndex=0};
$('#consoleForm').onsubmit=async e=>{e.preventDefault();const button=$('#executeConsole'),result=$('.console-result'),output=$('#consoleOutput'),meta=$('#consoleMeta'),body=Object.fromEntries(new FormData(e.target));button.disabled=true;button.textContent='执行中…';result.classList.remove('error');output.textContent='正在等待节点返回结果…';meta.textContent='';try{const value=await api('/console/execute',{method:'POST',body:JSON.stringify(body)});output.textContent=value.output||'(命令执行成功，没有输出)';meta.textContent=`${value.nodeName} · ${value.durationMs} ms`}catch(x){result.classList.add('error');output.textContent=[x.payload?.output,x.message].filter(Boolean).join('\n')||'执行失败';meta.textContent=x.payload?.nodeName?`${x.payload.nodeName} · ${x.payload.durationMs} ms`:'执行失败'}finally{button.disabled=false;button.textContent='执行命令'}};
const es=new EventSource('/api/events/stream');es.onopen=()=>{$('#health').textContent='实时连接'};es.onmessage=()=>scheduleRefresh();es.onerror=()=>{$('#health').textContent='重连中'};
$('#logout').onclick=async()=>{await fetch('/auth/logout',{method:'POST'});location.href='/'};
refresh().catch(e=>toast(e.message));setInterval(()=>scheduleRefresh(0),5000);
