let state={servers:[],experiments:[],events:[],transactions:[],workloads:[],accountSnapshots:[]}, metrics={};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const htmlCache=new Map(),optionCache=new WeakMap();
async function api(path,options={}){const r=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});if(!r.ok){const payload=await r.json(),error=new Error(payload.error||r.statusText);error.payload=payload;throw error}return r.status===204?null:r.json()}
function toast(s){const x=$('#toast');x.textContent=s;x.style.display='block';setTimeout(()=>x.style.display='none',3000)}
function status(s){return `<span class="status ${s==='failed'||s==='error'||s==='timeout'||String(s).includes('errors')?'failed':''}">${esc(s)}</span>`}
function short(s,n=18){s=String(s||'');return s.length>n?s.slice(0,n)+'…':s}
function age(s){return s?new Date(s).toLocaleString():'尚未查询'}
function hexDecimal(s){if(!s)return '—';try{return `${esc(s)} <small>(${BigInt(s).toString(10)})</small>`}catch{return esc(s)}}
function fmtUs(us){us=Number(us||0);if(us<=0)return '—';if(us<1000)return `${us} µs`;if(us<1000000)return `${(us/1000).toFixed(us<10000?2:1)} ms`;return `${(us/1000000).toFixed(2)} s`}
function txUs(t,name){return Number(t[name+'DurationUs']||0)||Number(t[name+'DurationMs']||0)*1000}
function diffUs(a,b){return a&&b?Math.max(0,(new Date(b)-new Date(a))*1000):0}
function patchHTML(selector,html){if(htmlCache.get(selector)===html)return false;htmlCache.set(selector,html);$(selector).innerHTML=html;return true}
function setOptions(select,html){if(optionCache.get(select)===html)return false;const selected=[...select.selectedOptions].map(x=>x.value);select.innerHTML=html;for(const option of select.options)option.selected=selected.includes(option.value);optionCache.set(select,html);return true}
function render(){
 const active=document.querySelector('.tab.active')?.id||'overview';
 $('#serverCount').textContent=state.servers.length;$('#nodeCount').textContent=state.experiments.reduce((n,e)=>n+(e.nodes?.length||0),0);$('#txCount').textContent=state.transactions.length;
 if(active==='servers')patchHTML('#serverRows',state.servers.map(s=>`<div class="row"><b>${esc(s.name)}</b> ${status(s.status)}<div class="meta"><span>${esc(s.user)}@${esc(s.host)}:${s.port}</span><span>${esc(s.workDir)}</span></div><button class="action" onclick="checkServer('${s.id}')">检查连接</button></div>`).join('')||'<div class="empty">尚未配置 SSH 服务器</div>');
 if(active==='experiments')setOptions($('#serverSelect'),state.servers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join(''));
 const exps=state.experiments.map(e=>`<div class="row"><b>${esc(e.name)}</b> ${status(e.status)}<div class="meta"><span>${e.nodes?.length||0} nodes</span><span>${esc(e.topology)}</span><span>${new Date(e.createdAt).toLocaleString()}</span></div>${(e.nodes||[]).map(n=>`<div class="meta"><span>${esc(n.name)} · ${status(n.status)}</span><span>block ${n.block}</span><span>${n.peers} peers</span><span>${esc(n.account||'')}</span></div>`).join('')}${e.error?`<p class="status failed">${esc(e.error)}</p>`:''}<button class="action" onclick="experiment('${e.id}','deploy')">部署/启动</button> <button class="action" onclick="experiment('${e.id}','stop')">停止</button> <a class="action" href="/api/experiments/${e.id}/report">导出报告</a></div>`).join('');
 if(active==='experiments')patchHTML('#experimentRows',exps||'<div class="empty">尚无实验</div>');
 if(active==='overview')patchHTML('#experimentCards',exps||'尚无实验');
 if(active==='transactions'){const running=state.experiments.filter(e=>e.status==='running'),runningOptions=running.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');setOptions($('#experimentSelect'),runningOptions);updateNodes();setOptions($('#workloadExperiment'),runningOptions);setOptions($('#consoleExperiment'),runningOptions);updateConsoleNodes();renderAccounts();renderTransactions();renderWorkloads()}
 if(active==='overview'){patchHTML('#metrics',[['确认交易',metrics.confirmed||0],['成功率',`${((metrics.successRate||0)*100).toFixed(1)}%`],['历史平均 TPS',(metrics.confirmedTPS||0).toFixed(4)],['端到端 p95',`${metrics.latencyP95Ms||0} ms`],['证明 p95',fmtUs(metrics.proofP95Us)],['验证 p95',fmtUs(metrics.verifyP95Us)]].map(x=>`<div class="metric"><b>${x[1]}</b><span>${x[0]}</span></div>`).join(''));patchHTML('#events',state.events.slice(-100).reverse().map(e=>`<div class="event ${e.level}"><time>${new Date(e.at).toLocaleTimeString()}</time>${esc(e.message)}</div>`).join(''))}
}
function renderTransactions(){const open=new Set([...document.querySelectorAll('#transactionRows .tx details[open]')].map(x=>x.closest('.tx')?.dataset.tx));const html=state.transactions.slice().reverse().map(t=>{const endToEnd=diffUs(t.submittedAt,t.confirmedAt),queue=diffUs(t.submittedAt,t.provingAt),chain=diffUs(t.broadcastAt,t.confirmedAt);let receipt='';try{receipt=JSON.stringify(JSON.parse(t.receipt),null,2)}catch{receipt=t.receipt}return `<div class="row tx" data-tx="${t.id}"><div><b>${esc(t.type)}</b> ${status(t.status)} ${t.workloadId?`<span class="workload-tag">自动 #${t.sequence}</span>`:''}</div><div class="meta"><span>${esc(t.fromNode)}${t.toNode?' → '+esc(t.toNode):' · 单节点状态交易'}</span><span>值 ${esc(t.value||'—')}</span><span>区块 ${esc(t.blockNumber||'—')}</span></div><div class="timings"><span>排队 ${fmtUs(queue)}</span><span>证明 ${fmtUs(txUs(t,'proof'))}</span><span>验证 ${fmtUs(txUs(t,'verify'))}</span><span>${t.status==='confirmed'?'链上确认 '+fmtUs(chain):'端到端 '+fmtUs(endToEnd)}</span></div>${t.status==='confirmed'?`<div class="meta"><span>端到端总耗时 ${fmtUs(endToEnd)}</span></div>`:''}${t.command?`<details class="tx-command"><summary>查看实际执行指令</summary><pre>${esc(t.command)}</pre></details>`:''}${t.hash?`<code title="${esc(t.hash)}">${esc(t.hash)}</code>`:''}${t.receipt?`<details><summary>查看链上 Receipt${t.receiptStatus?' · status '+esc(t.receiptStatus):''}</summary><pre>${esc(receipt)}</pre></details>`:''}${t.error?`<p class="status failed">${esc(t.error)}</p>`:''}</div>`}).join('')||'<div class="empty">尚无交易</div>';if(patchHTML('#transactionRows',html))for(const id of open){const d=document.querySelector(`#transactionRows [data-tx="${id}"] details`);if(d)d.open=true}}
function renderWorkloads(){const selected=$('#workloadExperiment').value,rows=state.workloads.filter(w=>!selected||w.experimentId===selected).slice().reverse();patchHTML('#workloadRows',rows.map(w=>{const txs=state.transactions.filter(t=>t.workloadId===w.id).sort((a,b)=>a.sequence-b.sequence),confirmed=txs.filter(t=>t.status==='confirmed').length,failed=txs.filter(t=>t.status==='failed'||t.status==='timeout').length,inflight=txs.length-confirmed-failed;return `<div class="row workload"><div><b>${esc(w.name)}</b> ${status(w.status)}</div><div class="meta"><span>${esc(w.type)} · ${esc(w.strategy)}</span><span>已投递 ${w.submitted}</span><span>成功 ${confirmed}</span><span>失败 ${failed}</span><span>处理中 ${inflight}</span></div><details><summary>查看实际节点路由（${txs.length} 笔）</summary>${txs.map(t=>`<div class="route"><b>#${t.sequence}</b><span>${esc(t.fromNode)}${t.toNode?' → '+esc(t.toNode):' · 单节点状态交易'}</span>${status(t.status)}</div>`).join('')||'<div class="empty">尚未投递</div>'}</details>${w.error?`<p class="status failed">${esc(w.error)}</p>`:''}</div>`}).join('')||'<div class="empty compact">尚无自动交易规则</div>')}
function renderAccounts(){const id=$('#experimentSelect').value,e=state.experiments.find(x=>x.id===id),nodes=e?.nodes||[],signature=JSON.stringify(nodes.map(n=>[n.id,n.name,n.status,n.account,n.publicBalance,n.zkBalance,n.commitment,n.lastTxBlock,n.stateError,n.peers]));if(htmlCache.get('#accountCards:signature')!==signature){htmlCache.set('#accountCards:signature',signature);patchHTML('#accountCards',nodes.map(n=>`<div class="account-card" data-node="${n.id}"><div class="account-title"><b>${esc(n.name)}</b>${status(n.status)}</div><code title="${esc(n.account)}">${esc(n.account||'无账户')}</code><dl><dt>公开余额（wei）</dt><dd>${esc(n.publicBalance||'—')}</dd><dt>隐私余额</dt><dd>${hexDecimal(n.zkBalance)}</dd><dt>承诺值</dt><dd title="${esc(n.commitment)}">${esc(short(n.commitment,30)||'—')}</dd><dt>隐私状态区块</dt><dd>${esc(n.lastTxBlock||'—')}</dd><dt>当前链高度</dt><dd data-block>${n.block||0}</dd><dt>最后查询</dt><dd data-seen>${age(n.lastSeen)}</dd></dl>${n.stateError?`<p class="warning">隐私状态：${esc(n.stateError)}</p>`:''}<button class="action" onclick="queryNode('${e.id}','${n.id}')">立即查询链上状态</button></div>`).join('')||'<div class="empty">请选择运行中的实验</div>')}for(const n of nodes){const card=document.querySelector(`#accountCards [data-node="${n.id}"]`);if(card){card.querySelector('[data-block]').textContent=n.block||0;card.querySelector('[data-seen]').textContent=age(n.lastSeen)}}const rows=(state.accountSnapshots||[]).filter(s=>s.experimentId===id).slice().reverse();patchHTML('#accountHistory',rows.map(s=>`<div class="history-row"><time>${age(s.at)}</time><b>${esc(s.nodeId)}</b><span>公开 ${esc(s.publicBalance||'—')}</span><span>隐私 ${hexDecimal(s.zkBalance)}</span><span>区块 ${s.chainBlock}</span><small>${esc(s.reason)}</small></div>`).join('')||'<div class="empty">首次查询或账户状态变化后会在这里留下记录</div>')}
function updateNodes(){const e=state.experiments.find(x=>x.id===$('#experimentSelect').value),options=(e?.nodes||[]).map(n=>`<option value="${n.id}">${esc(n.name)} · ${esc(n.status)}</option>`).join('');setOptions($('#nodeSelect'),options);setOptions($('#toNodeSelect'),options);updateCommandPreview()}
function updateCommandPreview(){const form=$('#transactionForm'),e=state.experiments.find(x=>x.id===form.elements.experimentId.value),from=e?.nodes?.find(x=>x.id===form.elements.fromNode.value),to=e?.nodes?.find(x=>x.id===form.elements.toNode.value),type=form.elements.type.value,value=form.elements.value.value||'0x1',q=JSON.stringify(value);let command='';if(!from){$('#transactionCommand').textContent='请选择运行中的实验和节点';return}if(type==='createAccount')command=`${from.name}: eth.sendCreateAccountTransaction({from:eth.accounts[0]})`;if(type==='mint')command=`${from.name}: eth.sendMintTransaction({from:eth.accounts[0],value:${q}})`;if(type==='redeem')command=`${from.name}: eth.sendRedeemTransaction({from:eth.accounts[0],value:${q}})`;if(type==='public')command=to?`${from.name}: eth.sendPublicTransaction({from:eth.accounts[0],to:${JSON.stringify(to.account)},value:${q}})`:'请选择目标节点';if(type==='transfer')command=to?`${from.name}: JSON.stringify(eth.getPayerNextState('0x01',${q}))\n${to.name}: eth.sendTransferTransaction({from:eth.accounts[0],value:${q},rs:'0x01',cmtANew:<payer.cmtANew>,snAOld:<payer.snAOld>,proofA:<payer.proofA>})`:'请选择目标节点';$('#transactionCommand').textContent=command}
function updateConsoleNodes(){const e=state.experiments.find(x=>x.id===$('#consoleExperiment').value),options=(e?.nodes||[]).filter(n=>n.status==='running').map(n=>`<option value="${n.id}">${esc(n.name)} · ${esc(n.account||'无账户')}</option>`).join('');setOptions($('#consoleNode'),options)}
let refreshing=false,refreshQueued=false,refreshTimer;async function refresh(){if(refreshing){refreshQueued=true;return}refreshing=true;try{[state,metrics]=await Promise.all([api('/state'),api('/metrics')]);render()}finally{refreshing=false;if(refreshQueued){refreshQueued=false;scheduleRefresh(100)}}}function scheduleRefresh(delay=250){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(e=>toast(e.message)),delay)}
async function checkServer(id){try{toast('正在检查 SSH…');await api(`/servers/${id}/check`,{method:'POST'});await refresh()}catch(e){toast(e.message);await refresh()}}
async function experiment(id,action){try{await api(`/experiments/${id}/${action}`,{method:'POST'});toast('任务已进入后台');await refresh()}catch(e){toast(e.message)}}
async function queryNode(experimentId,nodeId){try{toast('正在查询节点链上状态…');await api(`/experiments/${experimentId}/nodes/${nodeId}/state`,{method:'POST'});await refresh();toast('账户状态已更新')}catch(e){toast(e.message)}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');render()});
$('#serverForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));v.port=+v.port;try{await api('/servers',{method:'POST',body:JSON.stringify(v)});e.target.reset();await refresh()}catch(x){toast(x.message)}};
$('#experimentForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target)), ids=[...$('#serverSelect').selectedOptions].map(x=>x.value);const body={name:v.name,artifactPath:v.artifactPath,networkId:+v.networkId,p2pPortBase:+v.p2pPortBase,rpcPortBase:+v.rpcPortBase,topology:'full-mesh',placements:ids.map(serverId=>({serverId,count:+v.count}))};try{await api('/experiments',{method:'POST',body:JSON.stringify(body)});await refresh()}catch(x){toast(x.message)}};
$('#transactionForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{await api('/transactions',{method:'POST',body:JSON.stringify(body)});toast('交易已排队');await refresh()}catch(x){toast(x.message)}};$('#experimentSelect').onchange=()=>{updateNodes();renderAccounts()};
$('#transactionForm').addEventListener('input',updateCommandPreview);$('#transactionForm').addEventListener('change',updateCommandPreview);
$('#workloadForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.ratePerSecond=+body.ratePerSecond;body.durationSeconds=+body.durationSeconds;body.strategy='round-robin';try{await api('/workloads',{method:'POST',body:JSON.stringify(body)});toast('自动负载已启动');await refresh()}catch(x){toast(x.message)}};
$('#workloadExperiment').onchange=renderWorkloads;
$('#openConsole').onclick=()=>{const selected=$('#experimentSelect').value;if(selected)$('#consoleExperiment').value=selected;updateConsoleNodes();$('#nodeConsole').showModal();setTimeout(()=>$('#consoleCommand').focus(),0)};
$('#closeConsole').onclick=()=>$('#nodeConsole').close();$('#nodeConsole').onclick=e=>{if(e.target===$('#nodeConsole'))$('#nodeConsole').close()};$('#consoleExperiment').onchange=updateConsoleNodes;
document.querySelectorAll('.console-examples button').forEach(b=>b.onclick=()=>{$('#consoleCommand').value=b.dataset.command;$('#consoleCommand').focus()});
$('#consoleForm').onsubmit=async e=>{e.preventDefault();const button=$('#executeConsole'),result=$('.console-result'),output=$('#consoleOutput'),meta=$('#consoleMeta'),body=Object.fromEntries(new FormData(e.target));button.disabled=true;button.textContent='执行中…';result.classList.remove('error');output.textContent='正在等待节点返回结果…';meta.textContent='';try{const value=await api('/console/execute',{method:'POST',body:JSON.stringify(body)});output.textContent=value.output||'(命令执行成功，没有输出)';meta.textContent=`${value.nodeName} · ${value.durationMs} ms`}catch(x){result.classList.add('error');output.textContent=[x.payload?.output,x.message].filter(Boolean).join('\n')||'执行失败';meta.textContent=x.payload?.nodeName?`${x.payload.nodeName} · ${x.payload.durationMs} ms`:'执行失败'}finally{button.disabled=false;button.textContent='执行命令'}};
const es=new EventSource('/api/events/stream');es.onopen=()=>{$('#health').textContent='实时连接'};es.onmessage=()=>scheduleRefresh();es.onerror=()=>{$('#health').textContent='重连中'};
$('#logout').onclick=async()=>{await fetch('/auth/logout',{method:'POST'});location.href='/'};
refresh().catch(e=>toast(e.message));setInterval(()=>scheduleRefresh(0),5000);
