let state={servers:[],experiments:[],events:[],transactions:[],workloads:[],accountSnapshots:[]}, metrics={},buildProfile={},overviewExperimentId='',transactionExperimentId='',selectedServerIds=new Set();
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const htmlCache=new Map(),optionCache=new WeakMap(),recoveryRequests=new Set(),minerDrafts=new Map(),minerRequests=new Set();
let newMinerCountEdited=false;
async function api(path,options={}){const r=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});if(!r.ok){const payload=await r.json(),error=new Error(payload.error||r.statusText);error.payload=payload;throw error}return r.status===204?null:r.json()}
function toast(s){const x=$('#toast');x.textContent=s;x.style.display='block';setTimeout(()=>x.style.display='none',3000)}
function status(s){const kind=['failed','error','timeout','unreachable'].includes(s)||String(s).includes('errors')?'failed':s==='recovering'?'recovering':'';return `<span class="status ${kind}">${esc(s)}</span>`}
function short(s,n=18){s=String(s||'');return s.length>n?s.slice(0,n)+'…':s}
function age(s){return s?new Date(s).toLocaleString():'尚未查询'}
function hexDecimal(s){if(!s)return '—';try{return `${esc(s)} <small>(${BigInt(s).toString(10)})</small>`}catch{return esc(s)}}
function fmtUs(us){us=Number(us||0);if(us<=0)return '—';if(us<1000)return `${us} µs`;if(us<1000000)return `${(us/1000).toFixed(us<10000?2:1)} ms`;return `${(us/1000000).toFixed(2)} s`}
function txUs(t,name){return Number(t[name+'DurationUs']||0)||Number(t[name+'DurationMs']||0)*1000}
function transferTimings(t){if(t.type!=='transfer')return '';return `<div class="participant-timings"><b class="participant-title">Transfer 双方分阶段耗时</b><div class="participant-grid"><section><b>付款节点</b><span>证明生成 ${fmtUs(t.payerProofGenerationUs)}</span><span>证明验证 ${fmtUs(t.payerProofVerificationUs)}</span><span>交易/状态包生成 ${fmtUs(t.payerTxGenerationUs)}</span><span>交易验证 ${fmtUs(t.payerTxVerificationUs)}</span></section><section><b>收款节点</b><span>证明生成 ${fmtUs(t.receiverProofGenerationUs)}</span><span>证明验证 ${fmtUs(t.receiverProofVerificationUs)}</span><span>交易生成 ${fmtUs(t.receiverTxGenerationUs)}</span><span>交易验证 ${fmtUs(t.receiverTxVerificationUs)}</span></section></div></div>`}
function primaryTimings(t,queue,chain){const proof=t.type==='public'?'':`<span>证明生成 ${fmtUs(txUs(t,'proof'))}</span><span>证明验证 ${fmtUs(txUs(t,'verify'))}</span>`;return `<div class="timings"><span>排队 ${fmtUs(queue)}</span>${proof}<span>交易生成 ${fmtUs(t.txGenerationUs)}</span><span>交易验证 ${fmtUs(t.txVerificationUs)}</span><span>链上确认 ${fmtUs(chain)}</span></div>`}
function renderKeyProfiles(profile){const names=[['createaccount','CreateAccount'],['mint','Mint'],['redeem','Redeem'],['transfer','Transfer']],keys=profile.keys||{},durations=profile.keyDurationsMs||{};return `<div class="key-profiles">${names.map(([id,label])=>{const pk=Number(keys[id+'pk.txt']?.bytes||0),vk=Number(keys[id+'vk.txt']?.bytes||0);return `<section><b>${label}</b><span><strong>${fmtUs(Number(durations[id]||0)*1000)}</strong>密钥生成</span><span><strong>${pk?`${(pk/1048576).toFixed(2)} MiB`:'—'}</strong>pk 大小</span><span><strong>${vk?`${vk} B`:'—'}</strong>vk 大小</span></section>`}).join('')}</div>`}
function diffUs(a,b){return a&&b?Math.max(0,(new Date(b)-new Date(a))*1000):0}
function systemInfo(s){return Object.fromEntries(String(s||'').split('\n').filter(Boolean).map(line=>{const i=line.indexOf('=');return i<0?[line,'']:[line.slice(0,i),line.slice(i+1)]}))}
function pct(used,total){return total>0?`${Math.max(0,Math.min(100,used/total*100)).toFixed(1)}%`:'—'}
function newestFirst(items,dateField='createdAt'){return items.slice().sort((a,b)=>new Date(b[dateField]||b.createdAt||0)-new Date(a[dateField]||a.createdAt||0))}
function patchHTML(selector,html){if(htmlCache.get(selector)===html)return false;htmlCache.set(selector,html);$(selector).innerHTML=html;return true}
function setOptions(select,html){if(optionCache.get(select)===html)return false;const selected=[...select.selectedOptions].map(x=>x.value);select.innerHTML=html;for(const option of select.options)option.selected=selected.includes(option.value);optionCache.set(select,html);return true}
function serverLocked(id){return state.experiments.some(e=>['draft','running','deploying','stopping'].includes(e.status)&&(e.placements||[]).some(p=>p.serverId===id))}
function activeTx(t){return ['queued','proving','submitted'].includes(t.status)}
function privateAccountInitialized(experimentId,node){const block=String(node?.lastTxBlock||'').trim().toLowerCase();return (block&&block!=='0'&&block!=='0x0')||state.transactions.some(t=>t.experimentId===experimentId&&t.fromNode===node?.id&&t.type==='createAccount'&&t.status==='confirmed')}
function renderAccountInitialization(){
 const experimentId=$('#experimentSelect').value,e=state.experiments.find(x=>x.id===experimentId),nodes=e?.nodes||[];
 if(!e){patchHTML('#accountInitialization','<div class="empty compact">请选择实验后初始化隐私账户</div>');return}
 const experimentTxs=state.transactions.filter(t=>t.experimentId===experimentId),active=experimentTxs.filter(activeTx),busyNodes=new Set(active.flatMap(t=>[t.fromNode,t.toNode].filter(Boolean))),processing=new Set(active.filter(t=>t.type==='createAccount').map(t=>t.fromNode)),initialized=nodes.filter(n=>privateAccountInitialized(experimentId,n)),pending=nodes.filter(n=>!privateAccountInitialized(experimentId,n)),eligible=pending.filter(n=>n.status==='running'&&!n.privateStateError&&!busyNodes.has(n.id)),unavailable=pending.filter(n=>n.status!=='running'||n.privateStateError).length,busy=pending.filter(n=>n.status==='running'&&!n.privateStateError&&busyNodes.has(n.id)&&!processing.has(n.id)).length,failed=new Set(experimentTxs.filter(t=>t.type==='createAccount'&&['failed','timeout'].includes(t.status)&&pending.some(n=>n.id===t.fromNode)).map(t=>t.fromNode)).size,complete=nodes.length>0&&initialized.length===nodes.length;
 const label=complete?'已全部初始化':processing.size&&!eligible.length?'初始化进行中…':`初始化 ${eligible.length} 个待处理节点`,disabled=e.status!=='running'||!eligible.length;
 patchHTML('#accountInitialization',`<div class="initialization-head"><div><b>隐私账户初始化</b><span>每个参与隐私交易的节点在本实验中执行一次 CreateAccount</span></div><button id="initializeAccounts" type="button" class="action ${complete?'secondary':'primary'}" onclick="initializeAllAccounts()" ${disabled?'disabled':''}>${label}</button></div><div class="initialization-stats"><span><strong>${initialized.length}</strong> / ${nodes.length} 已初始化</span><span><strong>${processing.size}</strong> 处理中</span><span><strong>${eligible.length}</strong> 可初始化</span>${failed?`<span class="failed"><strong>${failed}</strong> 曾失败，可重试</span>`:''}${busy?`<span><strong>${busy}</strong> 节点忙</span>`:''}${unavailable?`<span><strong>${unavailable}</strong> 不可用</span>`:''}</div><p>${complete?'所有节点均已有链上隐私状态。':'部署只创建普通链上地址；此操作会发送真实交易并计入当前实验统计。已初始化或正忙的节点会自动跳过。'}</p>`)
}
function selectedServers(){return state.servers.filter(s=>selectedServerIds.has(s.id))}
function syncServerSelectionUI(){const selected=selectedServers(),all=state.servers.length>0&&selected.length===state.servers.length,hasLocal=selected.some(s=>s.host==='local'||s.host==='localhost-local'),hasLocked=selected.some(s=>serverLocked(s.id)),selectAll=$('#selectAllServers'),trust=$('#batchTrustServers'),remove=$('#batchDeleteServers');document.querySelectorAll('.server-select').forEach(x=>x.checked=selectedServerIds.has(x.dataset.serverId));selectAll.checked=all;selectAll.indeterminate=selected.length>0&&!all;$('#serverSelectionCount').textContent=`已选 ${selected.length} 台`;trust.disabled=!selected.length||hasLocal;trust.title=hasLocal?'本机服务器不需要信任 SSH 主机密钥':'';remove.disabled=!selected.length||hasLocked;remove.title=hasLocked?'选中项含有被草稿或活动实验使用的服务器':''}
function experimentActions(e){const active=['running','deploying','stopping'].includes(e.status),canDeploy=['draft','stopped','failed'].includes(e.status),miningBusy=e.miningStatus==='updating'||minerRequests.has(e.id);return `<div class="row-actions">${canDeploy?`<button class="action" onclick="experiment('${e.id}','deploy')" ${miningBusy?'disabled':''}>部署/启动</button>`:''}${e.status==='running'?`<button class="action secondary" onclick="experiment('${e.id}','stop')" ${miningBusy?'disabled title="请等待矿工配置调整完成"':''}>停止</button>`:''}<a class="action secondary" href="/api/experiments/${e.id}/report">导出报告</a>${active?'':`<button class="action danger" onclick="deleteExperiment('${e.id}')">删除</button>`}</div>`}
function experimentNodeCount(e){return e.nodes?.length||(e.placements||[]).reduce((sum,p)=>sum+Number(p.count||0),0)}
function configuredMinerCount(e){return Number(e.minerCount)>0?Number(e.minerCount):1}
function nodeIsMiner(e,n){return typeof n.isMiner==='boolean'?n.isMiner:Number(n.index)===1}
function miningStats(e){const nodes=e.nodes||[];return {target:configuredMinerCount(e),active:nodes.filter(n=>n.status==='running'&&n.mining===true).length,unknown:nodes.filter(n=>nodeIsMiner(e,n)&&(n.status!=='running'||typeof n.mining!=='boolean')).length}}
function miningNeedsReapply(e){return e.status==='running'&&(e.nodes||[]).some(n=>n.status==='running'&&typeof n.mining==='boolean'?n.mining!==nodeIsMiner(e,n):nodeIsMiner(e,n))}
function nodeMiningLabel(e,n){const miner=nodeIsMiner(e,n),available=n.status==='running',label=!available?'挖矿状态未知':n.mining===true?'正在挖矿':n.mining===false?'未挖矿':'待采集挖矿状态',kind=available&&n.mining===true?'working':available&&miner&&n.mining===false?'warning':'';return `<span class="node-mining-role ${kind}" title="${miner?'配置为矿工':'配置为普通节点'}；实际挖矿状态由节点 eth.mining 采集，节点不可达时不计入在线矿工">${miner?'矿工':'普通节点'} · ${label}</span>`}
function miningHealth(e){const s=miningStats(e);if(e.status!=='running')return `<span>矿工配置 ${s.target} 个</span>`;return `<span class="${s.active===s.target&&!s.unknown&&!miningNeedsReapply(e)?'':'miner-health-warning'}">矿工配置 ${s.target} · 在线挖矿 ${s.active}${s.unknown?` · ${s.unknown} 个配置矿工状态未知`:''}</span>`}
function minerConfiguration(e){
 const total=experimentNodeCount(e),count=configuredMinerCount(e),draft=minerDrafts.has(e.id)?minerDrafts.get(e.id):String(count),busy=e.miningStatus==='updating'||minerRequests.has(e.id),editable=['draft','stopped','running'].includes(e.status),valid=Number.isInteger(Number(draft))&&Number(draft)>=1&&Number(draft)<=total,changed=Number(draft)!==count;
 return `<section class="miner-configuration"><div class="miner-configuration-head"><b>出块配置</b><div class="meta">${miningHealth(e)}</div></div>${editable?`<form class="miner-count-form" data-miner-form="${e.id}" onsubmit="applyMinerCount(event,'${e.id}')"><label for="miners-${e.id}">矿工节点数<input id="miners-${e.id}" name="minerCount" type="number" min="1" max="${total}" step="1" required value="${esc(draft)}" data-miner-experiment="${e.id}" oninput="editMinerCount(this,'${e.id}')" ${busy?'disabled':''}></label><button type="submit" class="action secondary miner-apply" ${busy||!valid||(!changed&&!e.miningError&&!miningNeedsReapply(e))?'disabled':''}>${busy?'调整中…':e.miningError&&!changed?'重试应用':!changed&&miningNeedsReapply(e)?'重新应用':'应用配置'}</button></form>`:''}<p class="miner-config-hint">${e.status==='running'?'修改后直接调整现有节点的挖矿角色，不重新部署或清空数据。':'部署时按服务器轮流选择矿工，优先分散部署。'} 多矿工会改变总算力与出块节奏，性能对比时请保持配置一致。</p>${count===1?'<p class="miner-health-warning">当前只有 1 个配置矿工；它离线后，新交易将无法确认，直到恢复出块。</p>':''}${count>1?'<p class="miner-config-hint">多矿工会增加分叉概率；当前隐私状态树的运行中重组隔离尚有限制，请额外核对链与账户状态。</p>':''}${e.status==='running'&&miningStats(e).active===0&&!busy?'<p class="miner-health-warning">暂未观测到在线挖矿节点，请检查矿工连接与挖矿状态。</p>':''}${busy?'<p class="miner-config-progress" role="status">正在调整矿工，完成后会自动更新实际状态；请勿重复操作。</p>':''}${e.miningError?`<p class="node-recovery-error breakable" role="alert">矿工配置未完全生效：${esc(e.miningError)}。请核对各节点实际挖矿状态，再重试。</p>`:''}</section>`
}
function editMinerCount(input,id){minerDrafts.set(id,input.value);const e=state.experiments.find(x=>x.id===id),button=input.form.querySelector('.miner-apply');if(!e)return;button.disabled=!input.checkValidity()||(Number(input.value)===configuredMinerCount(e)&&!e.miningError&&!miningNeedsReapply(e))||e.miningStatus==='updating'||minerRequests.has(id)}
function renderExperimentRows(html){const focused=document.activeElement?.dataset?.minerExperiment;if(patchHTML('#experimentRows',html)&&focused)document.getElementById(`miners-${focused}`)?.focus({preventScroll:true})}
function updateMinerPlacement(){
 const form=$('#experimentForm'),input=form.elements.minerCount,selected=[...$('#serverSelect').selectedOptions],perServer=Number(form.elements.count.value),total=Number.isInteger(perServer)&&perServer>0?selected.length*perServer:0;
 input.max=String(Math.max(total,1));if(!newMinerCountEdited)input.value=String(Math.min(2,Math.max(total,1)));
 const miners=Number(input.value),valid=total>0&&Number.isInteger(miners)&&miners>=1&&miners<=total;
 input.setCustomValidity(total===0?'请先选择部署服务器并填写每台节点数':valid?'':`矿工节点数必须为 1 至 ${total} 的整数`);
 const coverage=Math.min(miners,selected.length),warning=miners===1?'仅 1 个矿工存在出块单点风险。':selected.length===1?'矿工都在同一台服务器上，无法抵御该服务器离线。':'';
 $('#minerPlacementPreview').innerHTML=total?`<b>${selected.length} 台服务器 · ${total} 个节点</b><span>${valid?`配置 ${miners} 个矿工，按服务器轮流选择，覆盖 ${coverage} 个服务器配置。`:`请设置 1 至 ${total} 个矿工。`}</span>${warning?`<span class="miner-health-warning">${warning}</span>`:''}<small>建议至少 2 个矿工分布在不同物理主机；多个服务器配置不一定代表独立主机。其余节点仍可参与交易和验证。</small>`:'先选择部署服务器，并填写每台节点数。';
}
async function applyMinerCount(event,id){
 event.preventDefault();const form=event.currentTarget,e=state.experiments.find(x=>x.id===id),minerCount=Number(form.elements.minerCount.value);if(!e||e.miningStatus==='updating'||minerRequests.has(id)||!form.reportValidity())return;
 if(e.status==='running'&&!confirm(`将实验“${e.name}”的矿工配置调整为 ${minerCount} 个？\n\n控制器会优先跨服务器选择矿工，并直接启停现有节点的挖矿任务；不会重启节点、清空数据或重发交易。\n\n总算力与出块节奏可能变化，本次调整会记录为实验事件。${minerCount===1?'\n注意：仅保留 1 个矿工会形成出块单点。':''}`))return;
 minerRequests.add(id);render();try{const result=await api(`/experiments/${id}/miners`,{method:'POST',body:JSON.stringify({minerCount})});minerDrafts.delete(id);toast(result?.miningStatus==='updating'||e.status==='running'?'矿工配置调整已进入后台，结果将自动更新':'矿工配置已保存');await refresh()}catch(error){toast(error.message);await refresh()}finally{minerRequests.delete(id);render()}
}
function nodeRecoveryAction(e,n){if(!['unreachable','recovering'].includes(n.status)&&!n.recoveryError&&!n.privateStateError)return '';const recovering=n.status==='recovering'||recoveryRequests.has(n.id),miningBusy=e.miningStatus==='updating'||minerRequests.has(e.id),disabled=miningBusy||e.status!=='running'||recovering;return `<button type="button" class="action secondary node-recover" onclick="recoverNode('${e.id}','${n.id}')" ${disabled?'disabled':''} title="${e.status!=='running'?'仅运行中的实验支持单节点恢复':miningBusy?'请等待矿工配置调整完成':'保留现有数据，检查进程并恢复连接'}">${recovering?'恢复中…':n.recoveryError?'重试恢复':'恢复节点'}</button>`}
function nodeRecoveryMessages(n){return `${n.privateStateError?`<p class="node-recovery-error breakable">隐私状态不可用：${esc(n.privateStateError)}<br>该节点的隐私交易已暂停，请先恢复节点；不要重复初始化账户。</p>`:''}${n.stateError?`<p class="warning node-state-error">连接 / 状态：${esc(n.stateError)}</p>`:''}${n.recoveryError?`<details class="node-recovery-error"><summary>最近恢复失败 · 查看详情</summary><pre>${esc(n.recoveryError)}</pre></details>`:''}${n.recoveryWarning?`<p class="warning node-recovery-warning">恢复提示：${esc(n.recoveryWarning)}</p>`:''}`}
function nodeRuntimeMetadata(n){return n.runtimeSha?`<div class="meta"><span title="当前节点运行包 SHA-256：${esc(n.runtimeSha)}">运行包 ${esc(short(n.runtimeSha,12))}</span></div>`:''}
function experimentDetail(e){const nodes=e.nodes||[],hasUnavailable=nodes.some(n=>['unreachable','recovering'].includes(n.status)||n.privateStateError||n.recoveryError);return `<div class="row experiment-detail" data-experiment="${e.id}"><div class="row-title"><b>${esc(e.name)}</b>${status(e.status)}</div><div class="meta"><span>${experimentNodeCount(e)} 个节点</span><span>${esc(e.topology)}</span><span>Network ID ${e.networkId}</span><span>${new Date(e.createdAt).toLocaleString()}</span>${e.recoveryArtifactSha?`<span title="单节点恢复首选运行包 SHA-256：${esc(e.recoveryArtifactSha)}；不会自动重启其他节点">首选恢复包 ${esc(short(e.recoveryArtifactSha,12))}</span>`:''}</div>${minerConfiguration(e)}${hasUnavailable?'<p class="node-recovery-hint">节点不可达或隐私状态异常时可单独恢复；保留原有链与账户数据，不重新部署实验，也不重发交易。服务器离线时，请先恢复服务器与 SSH 连接。</p>':''}<div class="node-list">${nodes.map(n=>`<div class="node-line"><span class="node-identity">${esc(n.name)} · ${status(n.status)}${nodeMiningLabel(e,n)}</span><span>区块 ${n.block||0}</span><span>${n.peers||0} peers</span><code title="${esc(n.account||'')}">${esc(short(n.account||'无账户',22))}</code><div class="node-line-action">${nodeRecoveryAction(e,n)}</div>${n.stateError||n.privateStateError||n.recoveryError||n.recoveryWarning||n.runtimeSha?`<div class="node-line-feedback">${nodeRuntimeMetadata(n)}${nodeRecoveryMessages(n)}</div>`:''}</div>`).join('')||'<span class="empty compact">尚未部署节点</span>'}</div>${e.error?`<p class="status failed breakable">${esc(e.error)}</p>`:''}${experimentActions(e)}</div>`}
function experimentSummary(e){const nodes=e.nodes||[],running=nodes.filter(n=>n.status==='running').length,maxBlock=nodes.reduce((n,x)=>Math.max(n,Number(x.block||0)),0),peers=nodes.reduce((n,x)=>n+Number(x.peers||0),0);return `<div class="overview-experiment"><div class="row-title"><b>${esc(e.name)}</b>${status(e.status)}</div><div class="experiment-stats"><div><b>${running}/${nodes.length}</b><span>节点在线</span></div><div><b>${maxBlock}</b><span>最高区块</span></div><div><b>${peers}</b><span>Peer 总数</span></div></div><div class="meta">${miningHealth(e)}</div><div class="meta"><span>${esc(e.topology)}</span><span>${new Date(e.createdAt).toLocaleString()}</span></div>${e.miningStatus==='updating'?'<p class="miner-config-progress" role="status">正在调整矿工配置…</p>':e.miningError?'<p class="miner-health-warning">矿工配置未完全生效，请管理实验并检查节点。</p>':''}${e.error?`<p class="status failed breakable">${esc(short(e.error,100))}</p>`:''}<button class="action secondary" onclick="showExperiment('${e.id}')">管理实验</button></div>`}
function render(){
 const active=document.querySelector('.tab.active')?.id||'overview';
	const recentExperiments=newestFirst(state.experiments);
 $('#serverCount').textContent=state.servers.length;$('#nodeCount').textContent=state.experiments.reduce((n,e)=>n+(e.nodes?.length||0),0);$('#txCount').textContent=state.transactions.length;
 if(active==='servers'){for(const id of [...selectedServerIds])if(!state.servers.some(s=>s.id===id))selectedServerIds.delete(id);patchHTML('#serverRows',state.servers.map(s=>{const x=systemInfo(s.systemInfo),cpus=Number(x.cpus||0),memory=Number(x.memory_kb||0),available=Number(x.memory_available_kb||0),disk=Number(x.disk_total_kb||0),diskAvailable=Number(x.disk_available_kb||0),load=Number(x.load1||0),locked=serverLocked(s.id);return `<div class="row server-row"><div class="row-title"><label class="server-card-select"><input class="server-select" type="checkbox" data-server-id="${s.id}" ${selectedServerIds.has(s.id)?'checked':''}><b>${esc(s.name)}</b></label>${status(s.status)}</div><div class="meta"><span>${esc(s.user)}@${esc(s.host)}:${s.port}</span><span>${esc(s.workDir)}</span>${s.p2pHost?`<span>P2P ${esc(s.p2pHost)}</span>`:''}</div><div class="server-load"><span><b>${load||'—'}</b>1 分钟负载${cpus?` / ${cpus} CPU`:''}</span><span><b>${pct(memory-available,memory)}</b>内存使用</span><span><b>${pct(disk-diskAvailable,disk)}</b>磁盘使用</span></div><div class="meta"><span>${esc(x.host||'')}</span><span>${esc(x.kernel||'')}</span><span>更新 ${age(s.lastCheck)}</span></div><div class="row-actions"><button class="action" onclick="checkServer('${s.id}')">立即刷新</button>${s.host==='local'||s.host==='localhost-local'?'':`<button class="action secondary" onclick="trustServer('${s.id}')">信任 SSH 主机密钥</button>`}<button class="action secondary" onclick="editServer('${s.id}')">编辑</button><button class="action danger" onclick="deleteServer('${s.id}')" ${locked?'disabled title="服务器正被草稿或活动实验使用"':''}>删除</button></div>${locked?'<p class="server-lock-hint">停止活动实验或删除引用它的草稿后，才可删除服务器；活动期间只能修改名称。</p>':''}</div>`}).join('')||'<div class="empty">尚未配置 SSH 服务器</div>');syncServerSelectionUI()}
 if(active==='experiments'){setOptions($('#serverSelect'),state.servers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join(''));updateMinerPlacement()}
	if(active==='experiments')patchHTML('#buildProfile',buildProfile.recordedAt?`<div class="build-summary"><span><b>${fmtUs(Number(buildProfile.libsnarkBuildDurationMs||0)*1000)}</b>电路编译</span><span><b>${fmtUs(Number(buildProfile.keyGenerationDurationMs||0)*1000)}</b>全部密钥生成</span><span><b>${buildProfile.cpus||'—'}</b>CPU 核心</span><span><b>${buildProfile.memoryKb?`${(buildProfile.memoryKb/1048576).toFixed(1)} GiB`:'—'}</b>主机内存</span></div><div class="meta"><span>${esc(buildProfile.host)}</span><span>${esc(buildProfile.kernel)}</span><span>${esc(buildProfile.cpuModel)}</span><span>${esc(buildProfile.compiler)}</span><span>${esc(buildProfile.recordedAt)}</span></div>${renderKeyProfiles(buildProfile)}`:'<div class="empty compact">下次执行 ./scripts/build-compatible-runtime.sh --generate-keys 后生成构建档案。</div>')
	const visibleExperiments=overviewExperimentId?recentExperiments.filter(e=>e.id===overviewExperimentId):recentExperiments,exps=recentExperiments.map(experimentDetail).join('');
 if(active==='experiments')renderExperimentRows(exps||'<div class="empty">尚无实验</div>');
	if(active==='overview'){setOptions($('#overviewExperiment'),`<option value="">全部实验</option>${recentExperiments.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}`);$('#overviewExperiment').value=overviewExperimentId;const scope=state.experiments.find(e=>e.id===overviewExperimentId);$('#overviewScopeHint').textContent=scope?`${scope.name} 的独立统计`:'全部实验的聚合统计';patchHTML('#experimentCards',visibleExperiments.map(experimentSummary).join('')||'尚无实验')}
	if(active==='transactions'){const running=newestFirst(state.experiments.filter(e=>e.status==='running'),'startedAt'),allOptions=recentExperiments.map(e=>`<option value="${e.id}">${esc(e.name)} · ${esc(e.status)}</option>`).join(''),runningOptions=running.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('');if(!state.experiments.some(e=>e.id===transactionExperimentId))transactionExperimentId=running[0]?.id||recentExperiments[0]?.id||'';setOptions($('#experimentSelect'),allOptions);$('#experimentSelect').value=transactionExperimentId;updateNodes();setOptions($('#consoleExperiment'),runningOptions);if(running.some(e=>e.id===transactionExperimentId))$('#consoleExperiment').value=transactionExperimentId;updateConsoleNodes();renderAccountInitialization();renderAccounts();renderTransactions();renderWorkloads()}
 if(active==='overview'){patchHTML('#metrics',[['确认交易',metrics.confirmed||0],['成功率',`${((metrics.successRate||0)*100).toFixed(1)}%`],['历史平均 TPS',(metrics.confirmedTPS||0).toFixed(4)],['端到端 p95',`${metrics.latencyP95Ms||0} ms`],['证明 p95',fmtUs(metrics.proofP95Us)],['验证 p95',fmtUs(metrics.verifyP95Us)]].map(x=>`<div class="metric"><b>${x[1]}</b><span>${x[0]}</span></div>`).join(''));const events=state.events.filter(e=>!overviewExperimentId||e.experimentId===overviewExperimentId);patchHTML('#events',events.slice(-100).reverse().map(e=>`<div class="event ${e.level}"><time>${new Date(e.at).toLocaleTimeString()}</time>${esc(e.message)}</div>`).join('')||'<div class="empty">该范围内尚无事件</div>')}
}
function renderTransactions(){const experimentId=$('#experimentSelect').value,e=state.experiments.find(x=>x.id===experimentId);$('#transactionScope').textContent=e?`${e.name} · 仅显示本实验记录`:'请选择实验';const open=new Set([...document.querySelectorAll('#transactionRows .tx details[open]')].map(x=>x.closest('.tx')?.dataset.tx));const html=state.transactions.filter(t=>t.experimentId===experimentId).slice().reverse().map(t=>{const endToEnd=diffUs(t.submittedAt,t.confirmedAt),queue=diffUs(t.submittedAt,t.provingAt),chain=diffUs(t.broadcastAt,t.confirmedAt);let receipt='';try{receipt=JSON.stringify(JSON.parse(t.receipt),null,2)}catch{receipt=t.receipt}return `<div class="row tx" data-tx="${t.id}"><div><b>${esc(t.type)}</b> ${status(t.status)} ${t.batchId?'<span class="workload-tag">批量初始化</span>':t.workloadId?`<span class="workload-tag">自动 #${t.sequence}</span>`:''}</div><div class="meta"><span>${esc(t.fromNode)}${t.toNode?' → '+esc(t.toNode):' · 单节点状态交易'}</span><span>值 ${esc(t.value||'—')}</span><span>区块 ${esc(t.blockNumber||'—')}</span></div>${primaryTimings(t,queue,chain)}${transferTimings(t)}${t.status==='confirmed'?`<div class="meta"><span>端到端总耗时 ${fmtUs(endToEnd)}</span></div>`:''}${t.command?`<details class="tx-command"><summary>查看实际执行指令</summary><pre>${esc(t.command)}</pre></details>`:''}${t.hash?`<code title="${esc(t.hash)}">${esc(t.hash)}</code>`:''}${t.receipt?`<details><summary>查看链上 Receipt${t.receiptStatus?' · status '+esc(t.receiptStatus):''}</summary><pre>${esc(receipt)}</pre></details>`:''}${t.error?`<p class="status failed">${esc(t.error)}</p>`:''}</div>`}).join('')||'<div class="empty">该实验尚无交易</div>';if(patchHTML('#transactionRows',html))for(const id of open){const d=document.querySelector(`#transactionRows [data-tx="${id}"] details`);if(d)d.open=true}}
function renderWorkloads(){const selected=$('#experimentSelect').value,rows=state.workloads.filter(w=>w.experimentId===selected).slice().reverse();patchHTML('#workloadRows',rows.map(w=>{const txs=state.transactions.filter(t=>t.workloadId===w.id).sort((a,b)=>a.sequence-b.sequence),confirmed=txs.filter(t=>t.status==='confirmed').length,failed=txs.filter(t=>t.status==='failed'||t.status==='timeout').length,inflight=txs.length-confirmed-failed;return `<div class="row workload"><div><b>${esc(w.name)}</b> ${status(w.status)}</div><div class="meta"><span>${esc(w.type)} · ${esc(w.strategy)}</span><span>已投递 ${w.submitted}</span><span>成功 ${confirmed}</span><span>失败 ${failed}</span><span>处理中 ${inflight}</span></div><details><summary>查看实际节点路由（${txs.length} 笔）</summary>${txs.map(t=>`<div class="route"><b>#${t.sequence}</b><span>${esc(t.fromNode)}${t.toNode?' → '+esc(t.toNode):' · 单节点状态交易'}</span>${status(t.status)}</div>`).join('')||'<div class="empty">尚未投递</div>'}</details>${w.error?`<p class="status failed">${esc(w.error)}</p>`:''}</div>`}).join('')||'<div class="empty compact">该实验尚无自动交易规则</div>')}
function renderAccounts(){
 const id=$('#experimentSelect').value,e=state.experiments.find(x=>x.id===id),nodes=e?.nodes||[],initializing=new Set(state.transactions.filter(t=>t.experimentId===id&&t.type==='createAccount'&&activeTx(t)).map(t=>t.fromNode)),signature=JSON.stringify([e?.status,e?.miningStatus,minerRequests.has(id),nodes.map(n=>[n.id,n.name,n.status,n.account,n.publicBalance,n.zkBalance,n.commitment,n.lastTxBlock,n.stateError,n.privateStateError,n.recoveryError,n.recoveryWarning,n.runtimeSha,n.peers,n.isMiner,n.mining,initializing.has(n.id),recoveryRequests.has(n.id)])]);
 if(htmlCache.get('#accountCards:signature')!==signature){
  htmlCache.set('#accountCards:signature',signature);
  patchHTML('#accountCards',nodes.map(n=>{const ready=privateAccountInitialized(id,n),initState=n.privateStateError?'状态异常':ready?'已初始化':initializing.has(n.id)?'初始化中':'待初始化',recovering=n.status==='recovering'||recoveryRequests.has(n.id);return `<div class="account-card" data-node="${n.id}"><div class="account-title"><b>${esc(n.name)}</b>${status(n.status)}</div>${nodeMiningLabel(e,n)}<span class="private-account-state ${n.privateStateError?'status failed':ready?'ready':initializing.has(n.id)?'working':'pending'}">隐私账户 · ${initState}</span><code title="${esc(n.account)}">${esc(n.account||'无账户')}</code>${nodeRuntimeMetadata(n)}<dl><dt>公开余额（wei）</dt><dd>${esc(n.publicBalance||'—')}</dd><dt>隐私余额</dt><dd>${hexDecimal(n.zkBalance)}</dd><dt>承诺值</dt><dd title="${esc(n.commitment)}">${esc(short(n.commitment,30)||'—')}</dd><dt>隐私状态区块</dt><dd>${esc(n.lastTxBlock||'—')}</dd><dt>当前链高度</dt><dd data-block>${n.block||0}</dd><dt>最后查询</dt><dd data-seen>${age(n.lastSeen)}</dd></dl>${nodeRecoveryMessages(n)}<div class="account-node-actions"><button type="button" class="action" onclick="queryNode('${e.id}','${n.id}')" ${recovering?'disabled':''}>立即查询链上状态</button>${nodeRecoveryAction(e,n)}</div>${n.status==='unreachable'?'<p class="node-recovery-hint">以上为最后一次成功查询的数据；恢复操作不会重新初始化账户。</p>':''}${recovering?'<p class="node-recovery-hint" role="status">正在检查进程、IPC 与节点连接，恢复结果将自动更新。</p>':''}</div>`}).join('')||'<div class="empty">请选择运行中的实验</div>');
 }
 for(const n of nodes){const card=document.querySelector(`#accountCards [data-node="${n.id}"]`);if(card){card.querySelector('[data-block]').textContent=n.block||0;card.querySelector('[data-seen]').textContent=age(n.lastSeen)}}
 const rows=(state.accountSnapshots||[]).filter(s=>s.experimentId===id).slice().reverse();patchHTML('#accountHistory',rows.map(s=>`<div class="history-row"><time>${age(s.at)}</time><b>${esc(s.nodeId)}</b><span>公开 ${esc(s.publicBalance||'—')}</span><span>隐私 ${hexDecimal(s.zkBalance)}</span><span>区块 ${s.chainBlock}</span><small>${esc(s.reason)}</small></div>`).join('')||'<div class="empty">首次查询或账户状态变化后会在这里留下记录</div>');
}
function transactionNodeOption(n,requireRunning=true){const unavailable=requireRunning?n.status!=='running':!n.account,suffix=unavailable?(requireRunning?'（不可用）':'（暂无账户地址）'):n.status!=='running'?'（可向已有地址收款）':n.privateStateError?'（隐私状态异常）':'';return `<option value="${n.id}" ${unavailable?'disabled':''}>${esc(n.name)} · ${esc(n.status)}${suffix}</option>`}
function presetTransactionProblem(){const form=$('#transactionForm'),e=state.experiments.find(x=>x.id===form.elements.experimentId.value),from=e?.nodes?.find(n=>n.id===form.elements.fromNode.value),type=form.elements.type.value,to=e?.nodes?.find(n=>n.id===form.elements.toNode.value);if(e?.status!=='running')return '请选择运行中的实验';if(!from)return '请选择可用的发送节点';if(from.status!=='running')return '发送节点不可用，请先恢复节点或选择其他在线节点';if(type!=='public'&&from.privateStateError)return '发送节点的隐私状态异常，请先恢复节点；不要重新初始化账户';if(type==='transfer'||type==='public'){if(!to)return '请选择可用的目标节点';if(type==='transfer'){if(to.status!=='running')return '目标节点不可用，请先恢复节点或选择其他在线节点';if(to.privateStateError)return '目标节点的隐私状态异常，请先恢复节点';if(from.id===to.id)return 'Transfer 的付款节点与收款节点不能相同'}else if(!to.account)return '目标节点尚无已知账户地址，请先查询链上状态'}if(type==='createAccount'&&privateAccountInitialized(e.id,from))return '该节点已经完成隐私账户初始化';return ''}
function updateNodes(){const experimentId=$('#experimentSelect').value,e=state.experiments.find(x=>x.id===experimentId),options=(e?.nodes||[]).map(n=>transactionNodeOption(n)).join('');$('#transactionExperimentId').value=experimentId;$('#workloadExperiment').value=experimentId;setOptions($('#nodeSelect'),options);updateDestinationOptions();const disabled=e?.status!=='running';$('#startWorkload').disabled=disabled;$('#transactionContextHint').textContent=e?`${e.status} · ${e.nodes?.length||0} 个节点 · Network ID ${e.networkId}${disabled?' · 历史查看模式':''}`:'暂无实验';updateCommandPreview()}
function updateDestinationOptions(){const form=$('#transactionForm'),e=state.experiments.find(x=>x.id===form.elements.experimentId.value),from=form.elements.fromNode.value,type=form.elements.type.value,nodes=e?.nodes||[],needsTarget=type==='transfer'||type==='public',choices=type==='transfer'?nodes.filter(n=>n.id!==from):nodes;setOptions($('#toNodeSelect'),choices.map(n=>transactionNodeOption(n,type==='transfer')).join(''));$('#targetNodeField').hidden=!needsTarget;$('#toNodeSelect').disabled=!needsTarget;$('#toNodeSelect').required=needsTarget;$('#transactionValueField').hidden=type==='createAccount';const problem=presetTransactionProblem();$('#queueTransaction').disabled=!!problem;$('#queueTransaction').title=problem;let hint=$('#presetTransactionHint');if(!hint){hint=document.createElement('p');hint.id='presetTransactionHint';hint.className='node-recovery-hint';hint.setAttribute('aria-live','polite');$('#queueTransaction').before(hint)}hint.textContent=problem;hint.hidden=!problem}
function updateCommandPreview(){const form=$('#transactionForm'),e=state.experiments.find(x=>x.id===form.elements.experimentId.value),from=e?.nodes?.find(x=>x.id===form.elements.fromNode.value),to=e?.nodes?.find(x=>x.id===form.elements.toNode.value),type=form.elements.type.value,value=form.elements.value.value||'0x1',q=JSON.stringify(value);let command='';if(!from){$('#transactionCommand').textContent='请选择运行中的实验和节点';return}if(type==='createAccount')command=`${from.name}: eth.sendCreateAccountTransaction({from:eth.accounts[0]})`;if(type==='mint')command=`${from.name}: eth.sendMintTransaction({from:eth.accounts[0],value:${q}})`;if(type==='redeem')command=`${from.name}: eth.sendRedeemTransaction({from:eth.accounts[0],value:${q}})`;if(type==='public')command=to?`${from.name}: eth.sendPublicTransaction({from:eth.accounts[0],to:${JSON.stringify(to.account)},value:${q}})`:'请选择目标节点';if(type==='transfer')command=to?`${from.name}: JSON.stringify(eth.getPayerNextState('0x01',${q}))\n${to.name}: eth.sendTransferTransaction({from:eth.accounts[0],value:${q},rs:'0x01',cmtANew:<payer.cmtANew>,snAOld:<payer.snAOld>,proofA:<payer.proofA>})`:'请选择目标节点';$('#transactionCommand').textContent=command}
function updateConsoleNodes(){const e=state.experiments.find(x=>x.id===$('#consoleExperiment').value),options=(e?.nodes||[]).filter(n=>n.status==='running').map(n=>`<option value="${n.id}">${esc(n.name)} · ${esc(n.account||'无账户')}</option>`).join('');setOptions($('#consoleNode'),options)}
let refreshing=false,refreshQueued=false,refreshTimer;async function refresh(){if(refreshing){refreshQueued=true;return}refreshing=true;try{[state,metrics,buildProfile]=await Promise.all([api('/state'),api(`/metrics${overviewExperimentId?'?experimentId='+encodeURIComponent(overviewExperimentId):''}`),api('/build-profile')]);if(overviewExperimentId&&!state.experiments.some(e=>e.id===overviewExperimentId)){overviewExperimentId='';metrics=await api('/metrics')}render()}finally{refreshing=false;if(refreshQueued){refreshQueued=false;scheduleRefresh(100)}}}function scheduleRefresh(delay=250){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(e=>toast(e.message)),delay)}
async function checkServer(id){try{toast('正在检查 SSH…');await api(`/servers/${id}/check`,{method:'POST'});await refresh()}catch(e){toast(e.message);await refresh()}}
async function trustServer(id){const server=state.servers.find(s=>s.id===id);if(!confirm(`请先通过可信渠道核对 ${server?.host||id} 的 SSH 主机指纹。\n\n确认采用首次使用信任（TOFU）并保存当前主机密钥吗？`))return;try{await api(`/servers/${id}/trust-host-key`,{method:'POST'});toast('主机密钥已保存，正在重新检查连接');await checkServer(id)}catch(e){toast(e.message)}}
async function batchTrustServers(){const servers=selectedServers();if(!servers.length||servers.some(s=>s.host==='local'||s.host==='localhost-local'))return;const names=servers.slice(0,8).map(s=>`${s.name} (${s.host})`).join('\n'),more=servers.length>8?`\n等 ${servers.length} 台服务器`:'';if(!confirm(`将扫描并保存以下服务器当前的 SSH 主机密钥：\n\n${names}${more}\n\n这是首次使用信任（TOFU）。请先通过可信渠道核对主机指纹，确认继续吗？`))return;const button=$('#batchTrustServers');button.disabled=true;button.textContent='信任中…';try{const result=await api('/servers/batch/trust-host-keys',{method:'POST',body:JSON.stringify({ids:servers.map(s=>s.id)})});toast(`已信任 ${result.trusted} 台服务器的主机密钥`);await refresh()}catch(e){toast(e.message)}finally{button.textContent='批量信任';syncServerSelectionUI()}}
async function batchDeleteServers(){const servers=selectedServers();if(!servers.length||servers.some(s=>serverLocked(s.id)))return;const names=servers.slice(0,10).map(s=>s.name).join('、'),more=servers.length>10?`等 ${servers.length} 台`:'';if(!confirm(`确定删除服务器配置：${names}${more}？\n\n本次操作会整批成功或整批失败；只删除 Lab 配置，不删除远端文件，历史实验记录会保留。`))return;const button=$('#batchDeleteServers');button.disabled=true;button.textContent='删除中…';try{const result=await api('/servers/batch/delete',{method:'POST',body:JSON.stringify({ids:servers.map(s=>s.id)})});for(const s of servers)selectedServerIds.delete(s.id);toast(`已删除 ${result.deleted} 台服务器配置`);await refresh()}catch(e){toast(e.message)}finally{button.textContent='批量删除';syncServerSelectionUI()}}
function resetServerForm(){const form=$('#serverForm');form.reset();form.elements.serverId.value='';form.elements.user.value='pfap';form.elements.port.value='22';form.elements.workDir.value='/opt/pfap-lab';$('#serverFormTitle').textContent='添加服务器';$('#saveServer').textContent='保存服务器';$('#cancelServerEdit').hidden=true}
function editServer(id){const s=state.servers.find(x=>x.id===id);if(!s)return;const form=$('#serverForm');for(const name of ['serverId','name','host','p2pHost','user','port','identityFile','workDir'])if(form.elements[name])form.elements[name].value=name==='serverId'?s.id:(s[name]??'');$('#serverFormTitle').textContent=`编辑服务器 · ${s.name}`;$('#saveServer').textContent='保存修改';$('#cancelServerEdit').hidden=false;form.scrollIntoView({behavior:'smooth',block:'center'})}
async function deleteServer(id){const s=state.servers.find(x=>x.id===id);if(!s||!confirm(`确定删除服务器配置“${s.name}”吗？\n\n只删除 Lab 中的配置，不会删除远端文件；历史实验记录会保留。`))return;try{await api(`/servers/${id}`,{method:'DELETE'});selectedServerIds.delete(id);if($('#serverForm').elements.serverId.value===id)resetServerForm();toast('服务器配置已删除');await refresh()}catch(e){toast(e.message)}}
function showExperiment(id){document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));document.querySelector('nav button[data-tab="experiments"]').classList.add('active');$('#experiments').classList.add('active');render();requestAnimationFrame(()=>document.querySelector(`[data-experiment="${id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}))}
async function experiment(id,action){try{await api(`/experiments/${id}/${action}`,{method:'POST'});toast('任务已进入后台');await refresh()}catch(e){toast(e.message)}}
async function deleteExperiment(id){const name=state.experiments.find(e=>e.id===id)?.name||id;if(!confirm(`确定删除实验“${name}”吗？\n\n该实验的交易、自动负载、账户快照和事件记录也会永久删除。`))return;try{await api(`/experiments/${id}`,{method:'DELETE'});toast('实验及关联记录已删除');await refresh()}catch(e){toast(e.message)}}
async function queryNode(experimentId,nodeId){try{toast('正在查询节点链上状态…');await api(`/experiments/${experimentId}/nodes/${nodeId}/state`,{method:'POST'});await refresh();toast('账户状态已更新')}catch(e){toast(e.message)}}
async function recoverNode(experimentId,nodeId){
 const experiment=state.experiments.find(e=>e.id===experimentId),node=experiment?.nodes?.find(n=>n.id===nodeId);
 if(!node||experiment.status!=='running'||experiment.miningStatus==='updating'||minerRequests.has(experimentId)||node.status==='recovering'||(node.status!=='unreachable'&&!node.recoveryError&&!node.privateStateError)||recoveryRequests.has(nodeId))return;
 if(!confirm(`恢复实验“${experiment.name}”中的 ${node.name}？\n\n将检查现有进程，使用${experiment.recoveryArtifactSha?'已配置的恢复运行包':'本实验原有运行包'}和原有数据恢复该节点及其连接。${experiment.recoveryArtifactSha?'\n需要应用恢复包时，会仅重启当前节点，不重启其他节点。':''}\n\n不会清空链数据、重新创建账户或重发交易。若服务器本身离线，请先恢复服务器与 SSH 连接。`))return;
 recoveryRequests.add(nodeId);render();
 try{await api(`/experiments/${experimentId}/nodes/${nodeId}/recover`,{method:'POST'});toast('恢复任务已启动，节点状态和结果将自动更新');await refresh()}catch(e){toast(e.message);await refresh()}finally{recoveryRequests.delete(nodeId);render()}
}
async function initializeAllAccounts(){const experimentId=$('#experimentSelect').value,e=state.experiments.find(x=>x.id===experimentId);if(!e||e.status!=='running')return;const active=state.transactions.filter(t=>t.experimentId===experimentId&&activeTx(t)),busyNodes=new Set(active.flatMap(t=>[t.fromNode,t.toNode].filter(Boolean))),eligible=(e.nodes||[]).filter(n=>n.status==='running'&&!n.privateStateError&&!privateAccountInitialized(experimentId,n)&&!busyNodes.has(n.id));if(!eligible.length){toast('当前没有可初始化的空闲节点');return}if(!confirm(`将在实验“${e.name}”中，为 ${eligible.length} 个节点各排入 1 笔 CreateAccount。\n\n这会初始化隐私账户、产生真实链上交易并计入实验统计；不会执行 Mint。已初始化、正忙或隐私状态异常的节点会自动跳过。`))return;const button=$('#initializeAccounts');if(button){button.disabled=true;button.textContent='正在排队…'}try{const result=await api(`/experiments/${experimentId}/initialize-accounts`,{method:'POST'}),details=[`已排队 ${result.queued} 笔`];if(result.alreadyInitialized)details.push(`已初始化 ${result.alreadyInitialized}`);if(result.busy)details.push(`正忙 ${result.busy}`);if(result.unavailable)details.push(`不可用 ${result.unavailable}`);toast(details.join(' · '));await refresh()}catch(x){toast(x.message);await refresh()}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');render()});
$('#serverForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target)),serverId=v.serverId;delete v.serverId;v.port=+v.port;try{await api(serverId?`/servers/${serverId}`:'/servers',{method:serverId?'PUT':'POST',body:JSON.stringify(v)});resetServerForm();toast(serverId?'服务器信息已更新':'服务器已添加');await refresh()}catch(x){toast(x.message)}};
$('#cancelServerEdit').onclick=resetServerForm;
$('#serverRows').addEventListener('change',e=>{const checkbox=e.target.closest('.server-select');if(!checkbox)return;if(checkbox.checked)selectedServerIds.add(checkbox.dataset.serverId);else selectedServerIds.delete(checkbox.dataset.serverId);syncServerSelectionUI()});
$('#selectAllServers').onchange=e=>{if(e.target.checked)for(const s of state.servers)selectedServerIds.add(s.id);else selectedServerIds.clear();syncServerSelectionUI()};
$('#batchTrustServers').onclick=batchTrustServers;$('#batchDeleteServers').onclick=batchDeleteServers;
$('#batchServerForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target)),hosts=[...new Set(v.hosts.split(/[\s,;]+/).map(x=>x.trim()).filter(Boolean))];v.hosts=hosts;v.port=+v.port;if(!hosts.length){toast('请至少输入一个 IP 或主机名');return}if(hosts.length>100){toast('单次最多添加 100 台服务器');return}try{const created=await api('/servers/batch',{method:'POST',body:JSON.stringify(v)});toast(`已添加 ${created.length} 台服务器`);e.target.reset();e.target.elements.namePrefix.value='worker';e.target.elements.user.value='pfap';e.target.elements.port.value='22';e.target.elements.workDir.value='/opt/pfap-lab';await refresh()}catch(x){toast(x.message)}};
$('#experimentForm').onsubmit=async e=>{e.preventDefault();updateMinerPlacement();if(!e.target.reportValidity())return;const v=Object.fromEntries(new FormData(e.target)), ids=[...$('#serverSelect').selectedOptions].map(x=>x.value);const body={name:v.name,artifactPath:v.artifactPath,networkId:+v.networkId,p2pPortBase:+v.p2pPortBase,rpcPortBase:+v.rpcPortBase,minerCount:+v.minerCount,topology:'full-mesh',placements:ids.map(serverId=>({serverId,count:+v.count}))};try{await api('/experiments',{method:'POST',body:JSON.stringify(body)});toast('实验已创建');await refresh()}catch(x){toast(x.message)}};
$('#experimentForm').addEventListener('input',e=>{if(e.target.name==='minerCount')newMinerCountEdited=true;if(['minerCount','count','serverId'].includes(e.target.name))updateMinerPlacement()});
$('#serverSelect').addEventListener('change',updateMinerPlacement);
$('#transactionForm').onsubmit=async e=>{e.preventDefault();const problem=presetTransactionProblem();if(problem){toast(problem);return}const body=Object.fromEntries(new FormData(e.target));try{await api('/transactions',{method:'POST',body:JSON.stringify(body)});toast('交易已排队');await refresh()}catch(x){toast(x.message)}};$('#experimentSelect').onchange=()=>{const id=$('#experimentSelect').value;transactionExperimentId=id;if(state.experiments.find(e=>e.id===id)?.status==='running')$('#consoleExperiment').value=id;updateNodes();updateConsoleNodes();renderAccountInitialization();renderAccounts();renderTransactions();renderWorkloads()};
$('#transactionForm').addEventListener('input',updateCommandPreview);$('#transactionForm').addEventListener('change',()=>{updateDestinationOptions();updateCommandPreview()});
$('#workloadForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));body.ratePerSecond=+body.ratePerSecond;body.durationSeconds=+body.durationSeconds;body.strategy='round-robin';try{await api('/workloads',{method:'POST',body:JSON.stringify(body)});toast('自动负载已启动');await refresh()}catch(x){toast(x.message)}};
$('#overviewExperiment').onchange=e=>{overviewExperimentId=e.target.value;refresh().catch(x=>toast(x.message))};
$('#openConsole').onclick=()=>{const selected=$('#experimentSelect').value;if(state.experiments.find(e=>e.id===selected)?.status==='running')$('#consoleExperiment').value=selected;updateConsoleNodes();$('#nodeConsole').showModal();setTimeout(()=>$('#consoleCommand').focus(),0)};
$('#closeConsole').onclick=()=>$('#nodeConsole').close();$('#nodeConsole').onclick=e=>{if(e.target===$('#nodeConsole'))$('#nodeConsole').close()};$('#consoleExperiment').onchange=updateConsoleNodes;
document.querySelectorAll('.console-examples button').forEach(b=>b.onclick=()=>{$('#consoleCommand').value=b.dataset.command;$('#consoleCommand').focus()});
$('#consolePreset').onchange=e=>{if(!e.target.value)return;$('#consoleCommand').value=e.target.value;$('#consoleCommand').focus();e.target.selectedIndex=0};
$('#consoleForm').onsubmit=async e=>{e.preventDefault();const button=$('#executeConsole'),result=$('.console-result'),output=$('#consoleOutput'),meta=$('#consoleMeta'),body=Object.fromEntries(new FormData(e.target));button.disabled=true;button.textContent='执行中…';result.classList.remove('error');output.textContent='正在等待节点返回结果…';meta.textContent='';try{const value=await api('/console/execute',{method:'POST',body:JSON.stringify(body)});output.textContent=value.output||'(命令执行成功，没有输出)';meta.textContent=`${value.nodeName} · ${value.durationMs} ms`}catch(x){result.classList.add('error');output.textContent=[x.payload?.output,x.message].filter(Boolean).join('\n')||'执行失败';meta.textContent=x.payload?.nodeName?`${x.payload.nodeName} · ${x.payload.durationMs} ms`:'执行失败'}finally{button.disabled=false;button.textContent='执行命令'}};
const es=new EventSource('/api/events/stream');es.onopen=()=>{$('#health').textContent='实时连接'};es.onmessage=()=>scheduleRefresh();es.onerror=()=>{$('#health').textContent='重连中'};
$('#logout').onclick=async()=>{await fetch('/auth/logout',{method:'POST'});location.href='/'};
refresh().catch(e=>toast(e.message));setInterval(()=>scheduleRefresh(0),5000);
