// View-only state: filtering and navigation never mutate experiments or transactions.
const experimentView={query:'',status:'',page:1,size:10,selected:''};
const transactionView={query:'',status:'',page:1,size:10,experimentId:''};
function workspacePage(items,view){const pages=Math.max(1,Math.ceil(items.length/view.size));view.page=Math.max(1,Math.min(pages,view.page));return {items:items.slice((view.page-1)*view.size,view.page*view.size),total:items.length,pages,page:view.page};}
function experimentInventory(){const q=experimentView.query.trim().toLowerCase();return workspacePage(newestFirst(state.experiments).filter(e=>(!q||[e.name,e.id,e.networkId].join(' ').toLowerCase().includes(q))&&(!experimentView.status||(experimentView.status==='attention'?['failed','interrupted','stop-failed'].includes(e.status)||!!e.error||!!e.miningError||(e.status==='running'&&(e.nodes||[]).some(n=>n.status==='unreachable'||n.privateStateError||n.recoveryError)):experimentView.status==='busy'?experimentBusy(e):e.status===experimentView.status))),experimentView);}
function workspacePagination(result,handler){return `<span>共 ${result.total} 条 · 第 ${result.page} / ${result.pages} 页 · 每页 10 条</span><div><button type="button" class="action secondary" onclick="${handler}(-1)" ${result.page<=1?'disabled':''}>上一页</button><button type="button" class="action secondary" onclick="${handler}(1)" ${result.page>=result.pages?'disabled':''}>下一页</button></div>`;}
function filterExperiments(key,value){experimentView[key]=value;experimentView.page=1;renderExperimentInventory();}
function resetExperimentFilters(){experimentView.query='';experimentView.status='';experimentView.page=1;$('#experimentSearch').value='';$('#experimentStatusFilter').value='';renderExperimentInventory();}
function pageExperiments(delta){experimentView.page+=delta;renderExperimentInventory();$('#experimentSearch').scrollIntoView({block:'nearest'});}
function selectExperiment(id){experimentView.selected=experimentView.selected===id?'':id;renderExperimentInventory();document.querySelector(`[data-manage-experiment="${id}"]`)?.focus({preventScroll:true});}
function openExperimentCreate(){const panel=$('#experimentCreate');panel.open=true;panel.scrollIntoView({behavior:'smooth',block:'start'});$('#experimentForm').elements.name.focus({preventScroll:true});}
function openExperimentTransactions(id){transactionExperimentId=id;document.querySelector('nav button[data-tab="transactions"]').click();$('#experimentSelect').focus({preventScroll:true});}
function renderExperimentInventory(){
 const result=experimentInventory();
 $('#experimentResultCount').textContent=`${result.total} / ${state.experiments.length} 个实验 · 按创建时间倒序`;
 renderExperimentRows(result.items.map(e=>{const nodes=e.nodes||[],running=nodes.filter(n=>n.status==='running').length,selected=experimentView.selected===e.id;return `<section class="experiment-entry"><div class="experiment-compact"><div class="experiment-name"><b>${esc(e.name)}</b><small>${esc(e.id)}</small></div><div>${status(e.status)}${e.error||e.miningError?'<small class="status failed">有操作异常，展开查看</small>':''}</div><div class="experiment-numbers"><span>${experimentNodeCount(e)} 节点 · ${running} 在线</span><small>矿工配置 ${configuredMinerCount(e)} · Network ${esc(e.networkId)}</small></div><time>${age(e.createdAt)}</time><div class="experiment-entry-actions"><button type="button" class="action secondary" onclick="openExperimentTransactions('${e.id}')">交易记录</button><button type="button" class="action" data-manage-experiment="${e.id}" aria-expanded="${selected}" aria-controls="experiment-panel-${e.id}" onclick="selectExperiment('${e.id}')">${selected?'收起管理':'展开管理'}</button></div></div>${deploymentProgress(e)}<div id="experiment-panel-${e.id}" ${selected?'':'hidden'}>${selected?experimentDetail(e):''}</div></section>`}).join('')||`<div class="empty">${state.experiments.length?'没有匹配的实验，请调整或重置筛选。':'尚无实验，点击“新建实验”开始配置。'}</div>`);
 patchHTML('#experimentPagination',workspacePagination(result,'pageExperiments'));
}
function transactionInventory(experimentId){if(transactionView.experimentId!==experimentId){transactionView.experimentId=experimentId;transactionView.page=1;}const q=transactionView.query.trim().toLowerCase();return workspacePage(newestFirst(state.transactions.filter(t=>t.experimentId===experimentId),'submittedAt').filter(t=>(!q||[t.id,t.type,t.fromNode,t.toNode,t.hash].join(' ').toLowerCase().includes(q))&&(!transactionView.status||(transactionView.status==='active'?activeTx(t):transactionView.status==='failed'?['failed','timeout'].includes(t.status):t.status===transactionView.status))),transactionView);}
function filterTransactions(key,value){transactionView[key]=value;transactionView.page=1;renderTransactions();}
function pageTransactions(delta){transactionView.page+=delta;renderTransactions();$('#transactionSearch').scrollIntoView({block:'nearest'});}
function renderTransactionInventory(experimentId){const result=transactionInventory(experimentId);$('#transactionResultCount').textContent=`${result.total} 条匹配记录 · 最新提交在前`;patchHTML('#transactionRows',result.items.map(transactionRow).join('')||'<div class="empty">没有匹配的交易记录，请检查所选实验和筛选条件。</div>');patchHTML('#transactionPagination',workspacePagination(result,'pageTransactions'));}
