// Run with Playwright available through NODE_PATH; all requests are intercepted.
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const output = fs.mkdtempSync(path.join(os.tmpdir(), 'pfap-server-ui-'));
const now = new Date().toISOString();
const worker = i => ({ id: `s${i}`, name: `worker-${i}`, host: `10.0.0.${i}`, hostGroup: i <= 11 ? 'pve-a' : 'pve-b', user: 'pfap', port: 22, workDir: '/srv/pfap-lab', status: i % 5 === 0 ? 'error' : i % 7 === 0 ? 'unknown' : 'online', lastCheck: now, lastSuccessAt: now, lastError: i % 5 === 0 ? 'SSH connection refused' : '', createdAt: new Date(2026, 0, i).toISOString(), systemInfo: 'host=worker\nload1=0.37\ncpus=8\nmemory_kb=16000000\nmemory_available_kb=8000000\ndisk_total_kb=104857600\ndisk_available_kb=524288\ndisk_path=/srv/pfap-lab' });
const fixture = { servers: Array.from({ length: 22 }, (_, i) => worker(i + 1)), experiments: [{ id: 'active', name: 'Existing mining experiment', status: 'running', minerCount: 1, minerMode: 'auto', placements: [{ serverId: 's1', count: 1 }], nodes: [], createdAt: now }], transactions: [], workloads: [], accountSnapshots: [], events: [] };
const writes = [], errors = [], consoleErrors = [];
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') consoleErrors.push(m.text()); });
    await page.addInitScript(() => { window.EventSource = class { constructor() { setTimeout(() => this.onopen?.(), 0); } }; window.setInterval = () => 0; });
    await page.route('**/*', async route => {
      const request = route.request(), endpoint = new URL(request.url()).pathname;
      if (endpoint.startsWith('/api/')) {
        let body = {};
        if (request.method() !== 'GET') writes.push({ endpoint, method: request.method(), body: request.postDataJSON() });
        if (endpoint === '/api/state') body = fixture;
        else if (['/api/metrics', '/api/build-profile', '/api/storage-health'].includes(endpoint)) body = {};
        else if (/^\/api\/servers\/s\d+\/network$/.test(endpoint) && request.method() === 'GET') body = {addresses:[{interface:'ens18',address:'192.168.50.219',prefix:24,state:'UP'},{interface:'ens19',address:'100.99.0.99',prefix:16,state:'UP'}]};
        else if (endpoint === '/api/servers/batch/host-group') {
          const input = request.postDataJSON();
          fixture.servers.filter(s => input.ids.includes(s.id)).forEach(s => { s.hostGroup = input.hostGroup; });
          body = { status: 'updated', updated: input.ids.length, hostGroup: input.hostGroup };
        } else if (endpoint === '/api/servers/batch/delete') {
          const ids = request.postDataJSON().ids;
          fixture.servers = fixture.servers.filter(s => !ids.includes(s.id)); body = { deleted: ids.length };
        } else if (endpoint === '/api/servers/batch') {
          const input = request.postDataJSON();
          assert.equal(input.hosts.length, 2);
          body = input.hosts.map((host, index) => ({ ...worker(30 + index), host, hostGroup: input.hostGroup }));
          fixture.servers.push(...body);
        } else if (/^\/api\/servers\/s\d+$/.test(endpoint) && request.method() === 'PUT') {
          body = Object.assign(fixture.servers.find(s => s.id === endpoint.split('/').at(-1)), request.postDataJSON());
        } else throw new Error('Unexpected mock API ' + request.method() + ' ' + endpoint);
        return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
      }
      const filename = endpoint === '/' ? 'index.html' : endpoint.slice(1);
      if (filename !== path.basename(filename) || !/\.(html|js|css)$/.test(filename)) return route.fulfill({ status: 404, body: '' });
      return route.fulfill({ status: 200, contentType: filename.endsWith('.js') ? 'text/javascript' : filename.endsWith('.css') ? 'text/css' : 'text/html', body: fs.readFileSync(path.join(__dirname, 'web', filename)) });
    });
    await page.goto('http://pfap-servers.fixture/');
    await page.waitForFunction(() => document.querySelector('#serverCount').textContent === '22');
    await page.locator('nav [data-tab="servers"]').click();
    const noOverflow = async label => {
      const sizes = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, dialogs: [...document.querySelectorAll('dialog[open]')].map(d => ({ scroll: d.scrollWidth, width: d.clientWidth })) }));
      assert.ok(sizes.scroll <= sizes.width + 1 && sizes.dialogs.every(d => d.scroll <= d.width + 1), label + JSON.stringify(sizes));
    };
    assert.equal(await page.locator('[data-server-row]').count(), 10);
    assert.equal(await page.locator('[data-server-row]').first().getAttribute('data-server-row'), 's1');
    assert.match(await page.locator('#serverSummary').innerText(), /22.*台服务器/s);
    assert.equal(await page.locator('#diskWarning details').evaluate(d => d.open), false);
    assert.equal(await page.locator('.hero').isVisible(), false);
    assert.ok(await page.locator('[data-server-row]').first().evaluate(el => el.getBoundingClientRect().bottom < innerHeight), 'first server row must fit initial desktop viewport');
    await noOverflow('desktop inventory');
    await page.screenshot({ path: path.join(output, 'desktop-inventory.png'), fullPage: true });
    await page.locator('#selectAllServers').check();
    await page.evaluate(() => { serverBatchPending = 'trust'; syncServerSelectionUI(); });
    assert.equal(await page.locator('[data-server-row="s1"] [data-server-action="edit"]').isDisabled(), true);
    await page.evaluate(() => { serverBatchPending = ''; syncServerSelectionUI(); });
    await page.locator('#serverNextPage').click();
    assert.match(await page.locator('#serverPageInfo').innerText(), /2 \/ 3/);
    assert.match(await page.locator('#serverSelectionCount').innerText(), /已选 10 台 · 10 台不在当前页/);
    await page.locator('[data-server-row="s11"] .server-select').check();
    await page.locator('#serverSearch').fill('10.0.0.22');
    assert.equal(await page.locator('[data-server-row]').count(), 1);
    assert.match(await page.locator('#serverSelectionCount').innerText(), /已选 11 台 · 11 台不在当前页/);
    await page.evaluate(() => refresh());
    assert.equal(await page.locator('#serverSearch').inputValue(), '10.0.0.22');
    assert.equal(await page.locator('#serverSearch').evaluate(el => el === document.activeElement), true);
    await page.locator('#serverSearch').fill('');
    await page.locator('#batchServerHostGroup').click();
    assert.match(await page.locator('#serverGroupScope').innerText(), /11 台.*1 台不在当前页/s);
    await page.locator('#serverGroupInput').fill('pve-new');
    page.once('dialog', dialog => { assert.match(dialog.message(), /worker-11.*不在当前页/); assert.match(dialog.message(), /不会自动切换/); return dialog.accept(); });
    await page.locator('#serverHostGroupForm button[type="submit"]').click();
    await page.waitForFunction(() => !document.querySelector('#serverHostGroupDialog').open);
    await page.waitForFunction(() => document.querySelector('[data-server-row="s1"]').textContent.includes('pve-new'));
    assert.equal(writes[0].body.ids.length, 11);
    assert.equal(fixture.experiments[0].minerCount, 1);
    await page.locator('#clearServerSelection').click();
    await page.locator('[data-server-row="s1"] .server-row-details > summary').click();
    fixture.servers[0].systemInfo = fixture.servers[0].systemInfo.replace('load1=0.37', 'load1=0.52');
    await page.evaluate(() => refresh());
    assert.equal(await page.locator('[data-detail-key="server:s1:details"]').evaluate(d => d.open), true);
    await page.locator('[data-server-row="s1"] [data-server-focus="s1:edit"]').click();
    assert.equal(await page.locator('#serverForm [name="host"]').evaluate(el => el.readOnly), true);
    assert.equal(await page.locator('#serverForm [name="hostGroup"]').evaluate(el => el.readOnly), false);
    await page.locator('#networkReadButton').click();
    await page.waitForFunction(() => document.querySelector('#serverNetworkChoice').options.length === 3);
    assert.equal(await page.locator('#serverNetworkChoice').isDisabled(), true);
    assert.match(await page.locator('#serverNetworkStatus').innerText(), /先安全停止/);
    await page.locator('#serverForm [name="name"]').fill('edited draft');
    await page.evaluate(() => refresh());
    assert.equal(await page.locator('#serverForm [name="name"]').inputValue(), 'edited draft');
    assert.equal(await page.locator('#serverForm [name="name"]').evaluate(el => el === document.activeElement), true);
    await noOverflow('desktop editor');
    await page.screenshot({ path: path.join(output, 'desktop-editor.png') });
    await page.locator('#serverForm [name="hostGroup"]').fill('pve-single');
    await page.locator('#saveServer').click();
    await page.waitForFunction(() => !document.querySelector('#serverEditor').open);
    await page.waitForFunction(() => document.querySelector('[data-server-row="s1"]').textContent.includes('edited draft'));
    assert.equal(writes[1].body.hostGroup, 'pve-single');
    await page.locator('#serverSearch').fill('pve-b');
    assert.equal(await page.locator('[data-server-row]').count(), 10);
    await page.locator('#serverConnectionFilter').selectOption('error');
    assert.equal(await page.locator('[data-server-row]').count(), 2);
    await page.locator('#serverSearch').fill(''); await page.locator('#serverConnectionFilter').selectOption('all');
    await page.locator('#serverPageSize').selectOption('20');
    assert.equal(await page.locator('[data-server-row]').count(), 20);
    await page.locator('#serverPageSize').selectOption('10');
    await page.locator('#serverNextPage').click(); await page.locator('#serverNextPage').click();
    await page.locator('#selectAllServers').check();
    page.once('dialog', dialog => dialog.accept());
    await page.locator('#batchDeleteServers').click();
    await page.waitForFunction(() => document.querySelector('#serverPageInfo').textContent === '第 2 / 2 页');
    assert.equal(fixture.servers.length, 20);
    await page.locator('#addBatchServers').click();
    await page.locator('#batchServerForm [name="hosts"]').fill('10.0.1.1\n10.0.1.2');
    await page.locator('#batchServerForm [name="hostGroup"]').fill('pve-batch');
    await page.locator('#batchServerForm button[type="submit"]').click();
    await page.waitForFunction(() => !document.querySelector('#serverEditor').open);
    assert.equal(writes[3].body.hostGroup, 'pve-batch');
    await page.setViewportSize({ width: 390, height: 844 });
    await noOverflow('mobile inventory');
    await page.screenshot({ path: path.join(output, 'mobile-inventory.png'), fullPage: true });
    await page.locator('#addServer').click();
    await noOverflow('mobile editor');
    await page.screenshot({ path: path.join(output, 'mobile-editor.png') });
    await page.keyboard.press('Escape');
    await page.evaluate(() => editServer('s2'));
    await page.locator('#networkReadButton').click();
    await page.locator('#serverNetworkChoice').selectOption('100.99.0.99');
    await page.evaluate(() => refresh());
    assert.equal(await page.locator('#serverForm [name="p2pHost"]').inputValue(), '100.99.0.99');
    assert.equal(fixture.servers.find(s => s.id === 's2').p2pHost, undefined);
    await noOverflow('mobile network picker');
    await page.screenshot({path:path.join(output,'mobile-network.png')});
    page.once('dialog',dialog=>{assert.match(dialog.message(),/不会修改 SSH、Web 或系统路由/);return dialog.dismiss()});
    await page.locator('#saveServer').click();
    assert.equal(fixture.servers.find(s => s.id === 's2').p2pHost, undefined);
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('#saveServer').click();
    await page.waitForFunction(() => !document.querySelector('#serverEditor').open);
    assert.equal(fixture.servers.find(s => s.id === 's2').p2pHost, '100.99.0.99');
    assert.equal(fixture.servers.find(s => s.id === 's2').host, '10.0.0.2');
    assert.deepEqual(errors, []); assert.deepEqual(consoleErrors, []);
    console.log(JSON.stringify({ ok: true, mockWrites: writes.length, desktop: '1440x1000', mobile: '390x844', screenshots: output }));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
