// All traffic is mocked. No controller or worker is contacted.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const output=fs.mkdtempSync(path.join(os.tmpdir(),'pfap-run-flow-'));
const now=new Date().toISOString(),nodes=Array.from({length:4},(_,i)=>({id:`n${i}`,name:`node-${i+1}`,index:i+1,serverId:'s',localIndex:i+1,status:'running',isMiner:i===0,mining:i===0,account:'0x'+'1'.repeat(40),zkBalance:'0x100',publicBalance:'100000',lastTxBlock:'0x1',lastSeen:now,peers:3}));
const fixture={servers:[{id:'s',name:'worker',host:'127.0.0.2',status:'online'}],experiments:[{id:'e',name:'Transfer 实验',status:'running',nodes,createdAt:now,startedAt:now,minerCount:1,placements:[]}],transactions:[],workloads:[],events:[],accountSnapshots:[]};
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.EventSource=class{};window.setInterval=()=>0});
 await page.route('**/*',route=>{const req=route.request(),url=new URL(req.url());if(url.pathname.startsWith('/api/')){if(req.method()!=='GET')writes.push({path:url.pathname,body:req.postDataJSON()});let result={};if(url.pathname==='/api/state')result=fixture;else if(url.pathname==='/api/workloads/preflight')result={ready:true,problems:[]};else if(url.pathname==='/api/workloads'&&req.method()==='POST'){result={...req.postDataJSON(),id:'w',status:'running',phase:'warmup',startedAt:now,submitted:0};fixture.workloads.push(result);}else if(url.pathname==='/api/workloads/w/stop'){fixture.workloads[0].status='draining';fixture.workloads[0].phase='draining';fixture.workloads[0].stopRequested=true;result=fixture.workloads[0];}else if(url.pathname==='/api/workloads/w/report')result={valid:false,windowSeconds:0,measurementSubmissions:0,confirmedSubmissions:0,pendingSubmissions:0,failedSubmissions:0,meanLatencyMs:null,observedConfirmedTPS:null,blocks:{count:0,validationSamples:0,missingValidationSamples:0},limitations:['尚未进入正式测量']};return route.fulfill({json:result});}const file=path.join(__dirname,'web',url.pathname==='/'?'index.html':url.pathname.slice(1));return route.fulfill({path:file,contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html'});});
 await page.goto('http://run.test/');await page.click('[data-tab="transactions"]');await page.waitForSelector('#runNodeSelect option');assert(await page.locator('#startWorkload').isDisabled());await page.getByRole('button',{name:'选择全部在线非矿工'}).click();assert.equal(await page.locator('#runNodeSelect').evaluate(s=>s.selectedOptions.length),3);
 await page.locator('#checkRunPlanButton').click();await page.waitForFunction(()=>!document.querySelector('#startWorkload').disabled);await page.locator('#workloadForm input[name="value"]').fill('0x2');assert(await page.locator('#startWorkload').isDisabled());await page.locator('#checkRunPlanButton').click();await page.waitForFunction(()=>!document.querySelector('#startWorkload').disabled);
 page.once('dialog',d=>d.dismiss());await page.locator('#startWorkload').click();assert.equal(writes.filter(w=>w.path==='/api/workloads').length,0);page.once('dialog',d=>d.accept());await page.locator('#startWorkload').click();await page.waitForSelector('.run-card');assert(await page.locator('#startWorkload').isDisabled());const submitted=writes.find(w=>w.path==='/api/workloads').body;assert.equal(submitted.type,'transfer');assert.equal(submitted.strategy,'ready-pool');assert.equal(submitted.nodeIds.length,3);assert.equal(submitted.durationSeconds,3600);assert.equal(submitted.warmupSeconds,600);
 await page.getByRole('button',{name:'查看窗口报告'}).click();await page.waitForSelector('.run-report');assert.match(await page.locator('.run-report').innerText(),/尚未进入正式测量/);
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});await page.locator('.workload-panel').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(output,`run-${width}.png`)});}
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'停止新增投递并收尾'}).click();await page.waitForFunction(()=>document.querySelector('.run-card').innerText.includes('收尾'));assert.equal(writes.filter(w=>w.path==='/api/workloads').length,1);assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,screenshots:output,mockWrites:writes.length,browserErrors:0}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
